In [1]:
import sys
import time
import pandas as pd
import numpy as np
import pickle

from sklearn.metrics import roc_auc_score, accuracy_score, classification_report
from scipy.stats import ks_2samp
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV
from datetime import datetime
from sklearn.preprocessing import LabelBinarizer
from scipy.stats import randint as sp_randint
from scipy.stats import uniform as sp_uniform
from sklearn import metrics
#from matplotlib import pyplot as plt
#from sklearn_pandas import DataFrameMapper
import gc

# 缺失值：常量
DEFAULT = -999

# %matplotlib inline

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

import warnings
warnings.filterwarnings("ignore")
from openpyxl import Workbook, load_workbook

In [3]:
sys.path.append('/home/zengjunyao/notebook/to_zjy_模型训练/')

In [4]:
from train_tools.model_train_tools import *
from train_tools.in_file.in_file import *

In [30]:
label = pd.read_parquet('/home/zengjunyao/notebook/to_zjy_模型训练/af/df_all_sample_afwf.parquet')
print(label.shape)

(77619, 105)

In [31]:
label['sample_type'].value_counts()

sample_type
train    51422
oot       2347
Name: count, dtype: int64

In [5]:
module_list = [
    #'app_th_base_v1','app_th_base_v2','app_th_bcate_v1','app_th_cashloan_v1',
    'app_th_cate_v1','app_th_gcate_v1','app_th_gcate_v2','app_th_loan_v1','app_th_loan_v2','sms_th_base_v1','sms_th_base_v2','sms_th_cate_v1','sms_th_comp_v1','sms_th_loan_v1','sms_th_loan0_v1',
'app_th_woe_v1_a4','app_th_woe_v2_a4','sms_th_sender_woe_v1_a4','sms_th_woe_v1_a4','sms_th_woe_v2_a4']

In [6]:
module_list = [
    'app_id_base_v3',
    'app_id_comp_v1',
    'app_id_cate_v1',
    'app_id_bcate_v2',
    'app_id_cashloan_v2',
    'app_id_gcate_v3',
    'app_id_loan_v3',
    'dev_id_base_v1',
    'fdc_id_base_v2',
    'sms_id_base_v2',
    'sms_id_loan_v1',
    'ui_id_base_v2',
    'loan_id_base_v4',
    'fdc_id_plt_v1',
    'fdc_id_query_v1']

In [7]:
import sys
from train_tools.tools_iv_csi.feature_filter import filter_features_by_iv_csi
from train_tools.tools_iv_csi.iv_csi_calculator import IVCSICalculator
#from tools_woe.ModelTools import saveTrainValidWoe
#def emptyData(length):    #创建一个指定长度的空DataFrame，用于后续的数据填充或占位
 #   return pd.DataFrame([np.nan for i in range(length)])

In [8]:

# 创建IV和CSI计算器实例
calculator = IVCSICalculator(
    bin_num=10, 
    good_event=1, 
    process_missing=True, 
    n_jobs = 1
)

In [ ]:
for module in module_list:
    print(f"开始处理模块: {module}")
    # 读取数据文件
    module_files1 = glob.glob(f'/home/zengjunyao/notebook/model_link/af/{module}/df_1_*.parquet')
    module_files2 = glob.glob(f'/home/zengjunyao/notebook/model_link/af/{module}/df_2_*.parquet')
    module_files3 = glob.glob(f'/home/zengjunyao/notebook/model_link/wf/{module}/df_1_*.parquet')
    module_files4 = glob.glob(f'/home/zengjunyao/notebook/model_link/wf/{module}/df_2_*.parquet')
    #module_files2 = glob.glob(f'/home/mahaocheng/workspace/data/th_old/loan_features/{module}/df_0_*.parquet')
    #module_files3 = glob.glob(f'/home/mahaocheng/workspace/data/th_old2/loan_features/{module}/df_0_*.parquet')
    module_files = module_files1 + module_files2 + module_files3 + module_files4
    if not module_files:
        print(f" {module} 没有找到parquet文件")
        continue
    module_df = concat_parquet_files(module_files)
    
    # 只保留数值型（float/int）列，去掉完全恒定的列
    df_numeric = module_df.select_dtypes(include=['number']).copy()
    # 保留 app_order_id
    if 'app_order_id' in module_df.columns:
        df_numeric.insert(0, 'app_order_id', module_df['app_order_id'].values)
    nunique = df_numeric.nunique(dropna=False)
    valid_columns = nunique[nunique > 1].index
    module_df = df_numeric[valid_columns].reset_index(drop=True)
    # label = pd.read_pickle('/home/mahaocheng/workspace/model_train/model_train_result/th_0_all_1017/label_allsample_merge.pickle')
    module_df = pd.merge(module_df, label[['app_order_id','label','sample_type']], on='app_order_id', how='inner')

    # 分割数据集
    train_data, test_data = train_test_split(module_df[module_df['sample_type'] == 'train'], train_size=0.85, random_state=2023)
    valid_data = module_df[module_df['sample_type'] == 'oot'].reset_index(drop=True)
    train_data = train_data.reset_index(drop=True)
    test_data = test_data.reset_index(drop=True)

    primaryKey = ['app_order_id','sample_type']
    target = ["label"]

    feature_train_ = train_data.drop(primaryKey, axis=1)
    feature_test_ = test_data.drop(primaryKey, axis=1)
    feature_valid_ = valid_data.drop(primaryKey, axis=1)
    x_train = feature_train_.drop('label', axis=1)
    x_test = feature_test_.drop('label', axis=1)
    x_valid = feature_valid_.drop('label', axis=1)
    y_train = feature_train_[['label']]
    y_test = feature_test_[['label']]
    y_valid = feature_valid_[['label']]
    
    col_list = x_train.columns.to_list()
    print(f"特征数量: {len(col_list)}")
    
    # 逐个计算
    iv_results = []
    csi_results = []
    train_woes = {}
    valid_woes = {}
    
    for i, col in enumerate(col_list):
        # if i % 100 == 0:
        #     print(f"处理进度: {i}/{len(col_list)}")
        try:
            train_data_single = feature_train_[['label', col]].copy()
            valid_data_single = feature_valid_[['label', col]].copy()
            train_data_single.reset_index(drop=True, inplace=True)
            valid_data_single.reset_index(drop=True, inplace=True)
            
            train_iv, train_woe_dict = calculator.calculate_iv_woe(train_data_single, 'label', col)
            valid_iv, valid_woe_dict = calculator.calculate_iv_woe(valid_data_single, 'label', col)
            csi_value = calculator.calculate_csi(train_data_single, valid_data_single, col)
            
            iv_results.append({'feature': col, 'iv_train': train_iv, 'iv_valid': valid_iv})
            csi_results.append({'feature': col, 'CSI': csi_value})
            train_woes[col] = train_woe_dict
            valid_woes[col] = valid_woe_dict

        except Exception as e:
            print(f"特征 {col} 计算失败: {str(e)}")
            continue
    
    iv = pd.DataFrame(iv_results)
    csi = pd.DataFrame(csi_results)
    iv['ratio'] = iv['iv_valid'] / iv['iv_train']
    iv_csi = pd.merge(iv, csi, on='feature', how='left')
    iv_csi = iv_csi.sort_values(by=["iv_train"], ascending=False)
    # 保存iv_csi
    output_file = f'/home/zengjunyao/notebook/to_zjy_模型训练/model_train_result/{module}_iv_csi_{datetime.now().strftime("%Y%m%d")}.csv'
    iv_csi.to_csv(output_file, index=False, encoding='utf_8_sig')
    feature_list_new = filter_features_by_iv_csi(module_df, iv_csi)
    print(f'{module}筛选前特征数量：',len(col_list) ,'筛选后特征数量：',len(feature_list_new))
    module_df = module_df[['app_order_id','label','sample_type'] + feature_list_new]
    #保存筛选后特征文件
    module_df.to_parquet(f'/home/zengjunyao/notebook/to_zjy_模型训练/af/{module}_filtered_feature.parquet')
    print(f"模块 {module} 处理完成\n")

开始处理模块: app_id_base_v3

正在加载parquet文件: 100%|██████████| 860/860 [00:14<00:00, 58.97it/s]

成功合并 860 个文件，总行数: 85506
特征数量: 1048
处理进度: 0/1048
处理进度: 100/1048
处理进度: 200/1048
处理进度: 300/1048
处理进度: 400/1048
处理进度: 500/1048
处理进度: 600/1048
处理进度: 700/1048
处理进度: 800/1048
处理进度: 900/1048
处理进度: 1000/1048
app_id_base_v3筛选前特征数量： 1048 筛选后特征数量： 42
模块 app_id_base_v3 处理完成

开始处理模块: app_id_comp_v1

正在加载parquet文件: 100%|██████████| 860/860 [00:30<00:00, 28.54it/s]

成功合并 860 个文件，总行数: 85514
特征数量: 2246
处理进度: 0/2246
处理进度: 100/2246
处理进度: 200/2246
处理进度: 300/2246
处理进度: 400/2246
处理进度: 500/2246
处理进度: 600/2246
处理进度: 700/2246
处理进度: 800/2246
处理进度: 900/2246
处理进度: 1000/2246
处理进度: 1100/2246
处理进度: 1200/2246
处理进度: 1300/2246
处理进度: 1400/2246
处理进度: 1500/2246
处理进度: 1600/2246
处理进度: 1700/2246
处理进度: 1800/2246
处理进度: 1900/2246
处理进度: 2000/2246
处理进度: 2100/2246
处理进度: 2200/2246
成功合并 860 个文件，总行数: 85506
特征数量: 2420
处理进度: 0/2420
处理进度: 100/2420
处理进度: 200/2420
处理进度: 300/2420
处理进度: 400/2420
处理进度: 500/2420
处理进度: 600/2420
处理进度: 700/2420
处理进度: 800/2420
处理进度: 900/2420
处理进度: 1000/2420
处理进度: 1100/2420
处理进度: 1200/2420
处理进度: 1300/2420
处理进度: 1400/2420
处理进度: 1500/2420
处理进度: 1600/2420
处理进度: 1700/2420
处理进度: 1800/2420
处理进度: 1900/2420
处理进度: 2000/2420
处理进度: 2100/2420
处理进度: 2200/2420
处理进度: 2300/2420
处理进度: 2400/2420
app_id_cashloan_v2筛选前特征数量： 2420 筛选后特征数量： 9
模块 app_id_cashloan_v2 处理完成

开始处理模块: app_id_gcate_v3

正在加载parquet文件: 100%|██████████| 860/860 [02:57<00:00,  4.85it/s]

成功合并 860 个文件，总行数: 85506
特征数量: 13483
处理进度: 0/13483
处理进度: 100/13483
处理进度: 200/13483
处理进度: 300/13483
处理进度: 400/13483
处理进度: 500/13483
处理进度: 600/13483
处理进度: 700/13483
处理进度: 800/13483
处理进度: 900/13483
处理进度: 1000/13483
处理进度: 1100/13483
处理进度: 1200/13483
处理进度: 1300/13483
处理进度: 1400/13483
处理进度: 1500/13483
处理进度: 1600/13483
处理进度: 1700/13483
处理进度: 1800/13483
处理进度: 1900/13483
处理进度: 2000/13483
处理进度: 2100/13483
处理进度: 2200/13483
处理进度: 2300/13483
处理进度: 2400/13483
处理进度: 2500/13483
处理进度: 2600/13483
处理进度: 2700/13483
处理进度: 2800/13483
处理进度: 2900/13483
处理进度: 3000/13483
处理进度: 3100/13483
处理进度: 3200/13483
处理进度: 3300/13483
处理进度: 3400/13483
处理进度: 3500/13483
处理进度: 3600/13483
处理进度: 3700/13483
处理进度: 3800/13483
处理进度: 3900/13483
处理进度: 4000/13483
处理进度: 4100/13483
处理进度: 4200/13483
处理进度: 4300/13483
处理进度: 4400/13483
处理进度: 4500/13483
处理进度: 4600/13483
处理进度: 4700/13483
处理进度: 4800/13483
处理进度: 4900/13483
处理进度: 5000/13483
处理进度: 5100/13483
处理进度: 5200/13483
处理进度: 5300/13483
处理进度: 5400/13483
处理进度: 5500/13483
处理进度: 5600/13483
处理进度: 5700/13483
处理进度: 5800/13483
处理进度: 5900/13483
处理进度: 6000/13483
处理进度: 6100/13483
处理进度: 6200/13483
处理进度: 6300/13483
处理进度: 6400/13483
处理进度: 6500/13483
处理进度: 6600/13483
处理进度: 6700/13483
处理进度: 6800/13483
处理进度: 6900/13483
处理进度: 7000/13483
处理进度: 7100/13483
处理进度: 7200/13483
处理进度: 7300/13483
处理进度: 7400/13483
处理进度: 7500/13483
处理进度: 7600/13483
处理进度: 7700/13483
处理进度: 7800/13483
处理进度: 7900/13483
处理进度: 8000/13483
处理进度: 8100/13483
处理进度: 8200/13483
处理进度: 8300/13483
处理进度: 8400/13483
处理进度: 8500/13483
处理进度: 8600/13483
处理进度: 8700/13483
处理进度: 8800/13483
处理进度: 8900/13483
处理进度: 9000/13483
处理进度: 9100/13483
处理进度: 9200/13483
处理进度: 9300/13483
处理进度: 9400/13483
处理进度: 9500/13483
处理进度: 9600/13483
处理进度: 9700/13483
处理进度: 9800/13483
处理进度: 9900/13483
处理进度: 10000/13483
处理进度: 10100/13483
处理进度: 10200/13483
处理进度: 10300/13483
处理进度: 10400/13483
处理进度: 10500/13483
处理进度: 10600/13483
处理进度: 10700/13483
处理进度: 10800/13483
处理进度: 10900/13483
处理进度: 11000/13483
处理进度: 11100/13483
处理进度: 11200/13483
处理进度: 11300/13483
处理进度: 11400/13483
处理进度: 11500/13483
处理进度: 11600/13483
处理进度: 11700/13483
处理进度: 11800/13483
处理进度: 11900/13483
处理进度: 12000/13483
处理进度: 12100/13483
处理进度: 12200/13483
处理进度: 12300/13483
处理进度: 12400/13483
处理进度: 12500/13483
处理进度: 12600/13483
处理进度: 12700/13483
处理进度: 12800/13483
处理进度: 12900/13483
处理进度: 13000/13483
处理进度: 13100/13483
处理进度: 13200/13483
处理进度: 13300/13483
处理进度: 13400/13483
app_id_gcate_v3筛选前特征数量： 13483 筛选后特征数量： 91
模块 app_id_gcate_v3 处理完成

开始处理模块: app_id_loan_v3

正在加载parquet文件: 100%|██████████| 860/860 [00:30<00:00, 28.13it/s]

成功合并 860 个文件，总行数: 85506
特征数量: 2272
处理进度: 0/2272
处理进度: 100/2272
处理进度: 200/2272
处理进度: 300/2272
处理进度: 400/2272
处理进度: 500/2272
处理进度: 600/2272
处理进度: 700/2272
处理进度: 800/2272
处理进度: 900/2272
处理进度: 1000/2272
处理进度: 1100/2272
处理进度: 1200/2272
处理进度: 1300/2272
处理进度: 1400/2272
处理进度: 1500/2272
处理进度: 1600/2272
处理进度: 1700/2272
处理进度: 1800/2272
处理进度: 1900/2272
处理进度: 2000/2272
处理进度: 2100/2272
处理进度: 2200/2272
app_id_loan_v3筛选前特征数量： 2272 筛选后特征数量： 25
模块 app_id_loan_v3 处理完成

开始处理模块: dev_id_base_v1

正在加载parquet文件: 100%|██████████| 860/860 [00:02<00:00, 397.65it/s]

成功合并 860 个文件，总行数: 85515
特征数量: 34
处理进度: 0/34
dev_id_base_v1筛选前特征数量： 34 筛选后特征数量： 3
模块 dev_id_base_v1 处理完成

开始处理模块: fdc_id_base_v2

正在加载parquet文件: 100%|██████████| 860/860 [07:45<00:00,  1.85it/s]

成功合并 860 个文件，总行数: 85415
特征数量: 32799
处理进度: 0/32799
处理进度: 100/32799
处理进度: 200/32799
处理进度: 300/32799
处理进度: 400/32799
处理进度: 500/32799
处理进度: 600/32799
处理进度: 700/32799
处理进度: 800/32799
处理进度: 900/32799
处理进度: 1000/32799
处理进度: 1100/32799
处理进度: 1200/32799
处理进度: 1300/32799
处理进度: 1400/32799
处理进度: 1500/32799
处理进度: 1600/32799
处理进度: 1700/32799
处理进度: 1800/32799
处理进度: 1900/32799
处理进度: 2000/32799
处理进度: 2100/32799
处理进度: 2200/32799
处理进度: 2300/32799
处理进度: 2400/32799
处理进度: 2500/32799
处理进度: 2600/32799
处理进度: 2700/32799
处理进度: 2800/32799
处理进度: 2900/32799
处理进度: 3000/32799
处理进度: 3100/32799
处理进度: 3200/32799
处理进度: 3300/32799
处理进度: 3400/32799
处理进度: 3500/32799
处理进度: 3600/32799
处理进度: 3700/32799
处理进度: 3800/32799
处理进度: 3900/32799
处理进度: 4000/32799
处理进度: 4100/32799
处理进度: 4200/32799
处理进度: 4300/32799
处理进度: 4400/32799
处理进度: 4500/32799
处理进度: 4600/32799
处理进度: 4700/32799
处理进度: 4800/32799
处理进度: 4900/32799
处理进度: 5000/32799
处理进度: 5100/32799
处理进度: 5200/32799
处理进度: 5300/32799
处理进度: 5400/32799
处理进度: 5500/32799
处理进度: 5600/32799
处理进度: 5700/32799
处理进度: 5800/32799
处理进度: 5900/32799
处理进度: 6000/32799
处理进度: 6100/32799
处理进度: 6200/32799
处理进度: 6300/32799
处理进度: 6400/32799
处理进度: 6500/32799
处理进度: 6600/32799
处理进度: 6700/32799
处理进度: 6800/32799
处理进度: 6900/32799
处理进度: 7000/32799
处理进度: 7100/32799
处理进度: 7200/32799
处理进度: 7300/32799
处理进度: 7400/32799
处理进度: 7500/32799
处理进度: 7600/32799
处理进度: 7700/32799
处理进度: 7800/32799
处理进度: 7900/32799
处理进度: 8000/32799
处理进度: 8100/32799
处理进度: 8200/32799
处理进度: 8300/32799
处理进度: 8400/32799
处理进度: 8500/32799
处理进度: 8600/32799
处理进度: 8700/32799
处理进度: 8800/32799
处理进度: 8900/32799
处理进度: 9000/32799
处理进度: 9100/32799
处理进度: 9200/32799
处理进度: 9300/32799
处理进度: 9400/32799
处理进度: 9500/32799
处理进度: 9600/32799
处理进度: 9700/32799
处理进度: 9800/32799
处理进度: 9900/32799
处理进度: 10000/32799

In [34]:
# 合并所有模块的特征数据
sample_list = [] 
for module in module_list:
    feature = pd.read_parquet(f'/home/zengjunyao/notebook/to_zjy_模型训练/af/{module}_filtered_feature.parquet')
    print(f'{module}：',feature.shape)
    sample_list.append(feature)

if len(sample_list) > 1:
    from functools import reduce
    sample = reduce(lambda left, right: pd.merge(left, right, on=['app_order_id','label','sample_type'], how='inner'), sample_list)
else:
    sample = sample_list[0].copy()
sample['sample_type'].fillna('train', inplace=True)
sample = sample.replace([np.inf, -np.inf], np.nan)
sample.fillna('-999', inplace=True)
print(sample.shape)

app_id_base_v3： (62985, 45)
app_id_comp_v1： (62992, 33)
app_id_cate_v1： (62992, 42)
app_id_bcate_v2： (62985, 5)
app_id_cashloan_v2： (62985, 12)
app_id_gcate_v3： (62985, 94)
app_id_loan_v3： (62985, 28)
dev_id_base_v1： (62993, 6)
fdc_id_base_v2： (62916, 1038)
sms_id_base_v2： (62985, 45)
sms_id_loan_v1： (62985, 13)
ui_id_base_v2： (62918, 6)
loan_id_base_v4： (62918, 349)
fdc_id_plt_v1： (62919, 3)
fdc_id_query_v1： (62914, 14)
(62913, 1691)

In [35]:
sample['sample_type'].value_counts()

sample_type
train    60568
oot       2345
Name: count, dtype: int64

In [36]:
print(sample.shape)
sample

(62913, 1691)

,app_order_id,label,sample_type,app_id_base_v3_install_mean_app_cnt_groupby_date_3d_7d_ratio,app_id_base_v3_install_day_cnt_15d,app_id_base_v3_update_day_cnt_15d_30d_ratio,app_id_base_v3_install_app_cnt_7d_15d_ratio,app_id_base_v3_install_var_app_cnt_groupby_date_60d_90d_ratio,app_id_base_v3_install_var_app_cnt_groupby_date_7d_15d_ratio,app_id_base_v3_install_app_cnt_60d_90d_ratio,app_id_base_v3_install_apply_last_days_diff_30d,app_id_base_v3_update_apply_first_days_diff_180d,app_id_base_v3_update_var_app_cnt_groupby_date_60d_90d_diff,app_id_base_v3_install_app_cnt_7d,app_id_base_v3_install_mean_app_cnt_groupby_date_3d,app_id_base_v3_install_avg_continuous_days_groupby_date_3d_7d_ratio,app_id_base_v3_install_mean_interval_day_groupby_date_7d,app_id_base_v3_install_first_last_days_diff_7d,app_id_base_v3_install_max_interval_day_groupby_date_180d,app_id_base_v3_install_time_density_7d,app_id_base_v3_install_app_cnt_3d_7d_ratio,app_id_base_v3_install_avg_continuous_days_groupby_date_7d_15d_ratio,app_id_base_v3_update_first_last_days_diff_90d,app_id_base_v3_update_day_cnt_30d_60d_ratio,app_id_base_v3_install_min_continuous_days_groupby_date_3d_7d_ratio,app_id_base_v3_install_day_cnt_infd,app_id_base_v3_update_mean_app_cnt_groupby_date_30d_60d_diff,app_id_base_v3_app_update_cnt,app_id_base_v3_update_day_cnt_60d_90d_ratio,app_id_base_v3_install_day_cnt_180d_infd_ratio,app_id_base_v3_update_time_density_180d,app_id_base_v3_update_day_cnt_infd,app_id_base_v3_install_max_app_cnt_groupby_date_3d_7d_ratio,app_id_base_v3_install_median_app_cnt_groupby_date_3d_7d_ratio,app_id_base_v3_install_median_continuous_days_groupby_date_7d_15d_ratio,app_id_base_v3_install_apply_last_days_diff_15d,app_id_base_v3_install_var_app_cnt_groupby_date_15d,app_id_base_v3_install_time_density_60d_90d_ratio,app_id_base_v3_update_apply_first_days_diff_60d_90d_ratio,app_id_base_v3_install_day_cnt_30d_60d_ratio,app_id_base_v3_update_mean_interval_day_groupby_date_30d_60d_ratio,app_id_base_v3_install_apply_last_days_diff_60d,app_id_base_v3_install_mean_app_cnt_groupby_date_7d,app_id_base_v3_install_app_cnt_3d,app_id_base_v3_update_app_cnt_30d_60d_ratio,app_id_comp_v1_seinst_updt_nonpreinst_iscomp_instdelmaxnull30_apply_start_diff_d7_0,app_id_comp_v1_seupdt_inst_iscomp_updt_end_start_diff_all_0,app_id_comp_v1_seupdt_inst_nonpreinst_iscomp_updt_end_start_diff_all_0,app_id_comp_v1_seinst_updt_iscomp_inst_day_avg_cnt_m6_0,app_id_comp_v1_up2in_updt_iscomp_up2in_time_diff_days_medium_d15_0,...,loan_id_base_v4_other_product_apply_overdue_days_std_in_inf_d,loan_id_base_v4_brush_order_third_loan_first_repay_time_diff,loan_id_base_v4_all_loan_success_inter_mean_rate_in_inf_d,loan_id_base_v4_self_app_pre_payoff_diff_mean_in_15_d,loan_id_base_v4_self_app_pre_payoff_diff_mean_in_15_orders,loan_id_base_v4_other_product_pre_payoff_overdue_days_mean_rate_in_15_orders,loan_id_base_v4_all_pre_payoff_inter_sum_in_15_orders,loan_id_base_v4_all_pre_payoff_overdue_days_mean_rate_in_15_d,loan_id_base_v4_other_app_pass_max_length_in_90_d,loan_id_base_v4_all_payoff_diff_mean_rate_in_15_orders,loan_id_base_v4_self_app_pre_payoff_diff_min_in_agg_180d,loan_id_base_v4_self_app_apply_diff_mean_in_15_orders,loan_id_base_v4_other_product_pre_payoff_diff_min_in_agg_90d,loan_id_base_v4_self_app_pre_payoff_inter_sum_in_7_orders,loan_id_base_v4_self_app_pre_payoff_diff_std_in_7_orders,loan_id_base_v4_all_pre_payoff_inter_mean_rate_in_30_d,loan_id_base_v4_other_product_pre_payoff_diff_range_in_7_orders,loan_id_base_v4_other_product_pre_payoff_overdue_days_mean_rate_in_90_d,loan_id_base_v4_all_payoff_inter_min_in_inf_d,loan_id_base_v4_self_app_pre_payoff_inter_mean_rate_in_7_d,loan_id_base_v4_all_pass_diff_mean_in_180_d,loan_id_base_v4_other_product_pre_payoff_inter_sum_in_7_orders,loan_id_base_v4_all_pre_payoff_overdue_days_mean_rate_in_30_d,loan_id_base_v4_brush_order_first_repay_early_day,loan_id_base_v4_all_loan_success_max_length_in_15_orders,loan_id_base_v4_self_app_payoff_diff_mean_in_agg_30d,loan_id_base_v4_self_app_pass_inter_min_in_15_orders,loan_id_base_v4_all_loan_success_amount_sum_min_in_agg_7d,loan_id_base_v4_other_product_pre_payoff_diff_sum_in_7_d,loan_id_base_v4_self_app_payoff_diff_mean_rate_in_3_orders,loan_id_base_v4_self_app_deny_diff_max_in_15_d,loan_id_base_v4_all_apply_amount_sum_max_in_agg_3d,loan_id_base_v4_other_product_pre_payoff_amount_mean_in_3_orders,loan_id_base_v4_all_pre_payoff_amount_sum_rate_in_7_d,loan_id_base_v4_other_product_loan_success_inter_mean_in_90_d,loan_id_base_v4_self_app_payoff_inter_std_in_3_orders,loan_id_base_v4_onloan_batch_pass_amount_sum,loan_id_base_v4_other_product_pre_payoff_diff_mean_in_15_d,loan_id_base_v4_all_pre_payoff_amount_mean_rate_in_90_d,fdc_id_query_v1_history_query_cnt_rto_d3_d30,fdc_id_query_v1_d3_records_num_max,fdc_id_query_v1_d3_records_num_std,fdc_id_query_v1_history_query_cnt_rto_d3_d99999,fdc_id_query_v1_history_query_cnt_rto_d90_d180,fdc_id_query_v1_history_query_cnt_rto_d7_d30,fdc_id_query_v1_history_query_cnt_rto_d180_d90,fdc_id_query_v1_history_query_cnt_diff_d30_d99999,fdc_id_query_v1_history_query_cnt_d30,fdc_id_query_v1_history_query_cnt_rto_d3_d7,fdc_id_query_v1_history_query_cnt_d90
0,1320537427509161985,0,train,1.2857,6.0,0.5882,0.5385,1.1630,1.3793,0.8667,2.0,175.0,8.3038,7.0,3.0000,1.0000,3.0,6.0,36.0,0.6009,0.4286,0.8333,89.0,0.8500,1.0000,77.0,0.4588,193.0,0.7143,0.2338,0.2264,88.0,1.0,1.0000,1.0000,2.0,0.9667,1.2882,0.6517,0.7500,0.6142,2.0,2.3333,3.0,0.9196,260,47,47,1.8297,128.0,...,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0,-999.0000,-999.0000,0.0,-999.0,-999.0000,4.333333,1155,0.800000,7.666667,1.000000,1.733333,1.000000,20,26,2.500000,36
1,1320534997908238337,1,train,1.0000,10.0,0.5833,0.3571,1.0390,1.8750,0.9062,1.0,164.0,0.5496,5.0,1.6667,1.0000,1.0,2.0,67.0,1.0000,1.0000,1.2000,77.0,0.8276,1.0000,45.0,0.0072,86.0,0.8788,0.6222,0.3342,50.0,1.0,1.0000,1.5000,1.0,0.7111,0.6981,0.5897,0.9524,0.7845,1.0,1.6667,5.0,0.8295,27,67,67,23.6842,0.0,...,1.0954,3463.0,0.0000,0.0000,1.3877,2.0000,51.7244,2.0,-999.0,0.6051,4.1631,2.2933,-999.0,35.6710,0.0000,1.8484,0.0,2.0000,11.8903,0.0,-999.0000,35.6710,1.7500,1.6553,1.0,4.1631,0.0000,1000000.0,-999.0,0.0000,10.4765,3800000.0,-999.0,0.0,0.0000,-999.0000,0.0,0.0,0.9091,4.000000,44,0.000000,6.400000,1.000000,3.333333,1.000000,12,20,1.200000,31
2,1320538380933181440,0,train,-999.0000,2.0,0.8000,0.0000,1.0000,-999.0000,1.0000,13.0,83.0,0.0707,0.0,-999.0000,-999.0000,-999.0,-999.0,88.0,-999.0000,-999.0000,-999.0000,82.0,0.7500,-999.0000,14.0,0.1833,46.0,0.8000,0.5000,0.2435,29.0,-999.0,-999.0000,-999.0000,13.0,0.5000,1.0000,0.6386,0.8333,0.7569,13.0,-999.0000,0.0,0.8140,30,16,16,25.0000,21.5,...,1.1547,357014.0,1.1424,0.0000,3.9463,3.0000,31.1874,2.0,-999.0,1.2651,7.8926,3.1194,-999.0,31.1874,5.5809,1.2691,-999.0,3.0000,7.7649,0.0,-999.0000,7.7649,1.6667,1.6130,1.0,7.8926,18.7163,300000.0,-999.0,0.0000,4.0352,300000.0,-999.0,0.0,0.0000,-999.0000,300000.0,-999.0,1.0370,14.000000,10,0.000000,31.000000,1.000000,14.000000,1.000000,17,14,1.000000,31
3,1320545624303251456,1,train,1.2321,10.0,0.6522,0.8235,1.0000,0.9706,1.0000,1.0,179.0,0.9160,28.0,5.7500,0.6667,1.0,5.0,42.0,0.0000,0.8214,1.2000,86.0,0.6765,0.6667,65.0,1.1854,145.0,0.8718,0.5077,0.2547,58.0,1.0,1.5000,1.2000,1.0,6.0444,1.0000,0.7093,0.6957,0.7377,1.0,4.6667,23.0,0.8671,20,44,44,15.0943,0.0,...,-999.0000,-999.0,0.9273,7.4193,-999.0000,0.0000,-999.0000,1.0,12.0,0.0000,7.4193,0.3515,-999.0,-999.0000,-999.0000,2.0183,-999.0,1.0000,7.5346,0.0,0.3077,-999.0000,1.0000,0.3445,15.0,7.4193,1.6136,600000.0,-999.0,0.0000,7.5346,1800000.0,-999.0,0.0,5.1896,-999.0000,600000.0,-999.0,0.9330,6.200000,17,0.000000,8.000000,1.026316,4.428571,0.974359,9,31,1.400000,38
4,1320537427513356289,0,train,1.2857,6.0,0.5882,0.5385,1.1630,1.3793,0.8667,2.0,175.0,8.3038,7.0,3.0000,1.0000,3.0,6.0,36.0,0.6009,0.4286,0.8333,89.0,0.8500,1.0000,77.0,0.4588,193.0,0.7143,0.2338,0.2264,88.0,1.0,1.0000,1.0000,2.0,0.9667,1.2882,0.6517,0.7500,0.6142,2.0,2.3333,3.0,0.9196,260,47,47,1.8297,128.0,...,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0,-999.0000,-999.0000,0.0,-999.0,-999.0000,4.333333,1155,0.800000,7.666667,1.000000,1.733333,1.000000,20,26,2.500000,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62908,1424419841429356544,0,train,1.0000,2.0,0.8571,0.6667,1.0000,-999.0000,1.0000,0.0,52.0,0.0000,2.0,2.0000,1.0000,-999.0,0.0,15.0,-999.0000,1.0000,1.0000,52.0,0.8750,1.0000,8.0,0.0536,10.0,1.0000,0.3750,0.6157,10.0,1.0,1.0000,1.0000,0.0,0.5000,1.0000,1.0000,1.0000,0.4487,0.0,2.0000,2.0,0.9091,0,0,0,100.0000,0.0,...,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0,-999.0000,-999.0000,0.0,-999.0,-999.0000,3.333333,25,1.291758,3.666667,1.000000,1.666667,1.000000,3,30,2.000000,33
62909,1424419841429356545,0,train,1.0000,2.0,0.8571,0.6667,1.0000,-999.0000,1.0000,0.0,52.0,0.0000,2.0,2.0000,1.0000,-999.0,0.0,15.0,-999.0000,1.0000,1.0000,52.0,0.8750,1.0000,8.0,0.0536,10.0,1.0000,0.3750,0.6157,10.0,1.0,1.0000,1.0000,0.0,0.5000,1.0000,1.0000,1.0000,0.4487,0.0,2.0000,2.0,0.9091,0,0,0,100.0000,0.0,...,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0000,-999.0000,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0000,-999.0000,-999.0,-999.0,-999.0,-999.0000,-999.0000,0.0,-999.0,-999.0000,3.333333,25,1.291758,3.666667,1.000000,1.666667,1.000000,3,30,2.000000,33
62910,1424407116078792705,0,train,1.0000,3.0,0.8571,0.6667,-999.0000,-999.0000,0.8750,0.0,172.0,0.1211,2.0,1.0000,1.0000,1.0,1.0,76.0,1.0000,1.0000,1.3333,81.0,0.7778,1.0000,26.0,0.2540,38.0,0.9474,0.3462,0.3931,28.0,1.0,1.0000,1.3333,0.0,0.0000,1.1017,0.6914,0.7143,0.4670,0.0,1.0000,2.0,0.8824,65,8,8,9.2308,11.0,...,-999.0000,-999.0,0.0000,-999.0000,-999.0000,1.0000,4.3254,1.0,-999.0,-999.0000,-999.0000,4.3254,-999.0,4.3254,-999.0000,2.0000,-999.0,1.0000,4.3254,2.0,-999.0000,4.3254,1.0000,1.1036,1.0,-999.0000,-999.0000,750000.0,0.0,-999.0000,4.3254,750000.0,750000.0,0.5,0.0000,-999.0000,750000.0,-999.0,1.0000,6.333333,57,0.000000,11.000000,1.600000,2.714286,0.625000,14,19,2.333333,20
62911,1424411129209831424,0,train,1.0000,2.0,0.5000,0.5000,1.1150,-999.0000,0.9524,3.0,146.0,0.2821,1.0,1.0000,1.0000,-999.0,0.0,34.0,-999.0000,1.0000,1.0000,78.0,0.6667,1.0000,23.0,0.8333,115.0,0.8684,0.7391,0.4769,43.0,1.0,1.0000,1.0000,3.0,0.0000,1.1235,0.7308,0.5385,0.7753,3.0,1.0000,1.0,0.8015,65,32,32,55.5556,20.0,...,-999.0000,-999.0,1.0360,-999.0000,-999.0000,1.0000,11.1164,1.0,-999.0,-999.0000,-999.0000,6.4125,-999.0,11.1164,-999.0000,1.1279,-999.0,1.0000,11.1164,0.0,7.4999,11.1164,1.0000,1.0419,3.0,-999.0000,17.0628,1850000.0,-999.0,-999.0000,11.1164,1850000.0,750000.0,0.0,14.0448,-999.0000,1850000.0,-999.0,0.9278,4.000000,16,0.942809,5.285714,1.000000,2.333333,1.000000,9,28,1.714286,37
62912,1424436008042774528,0,train,1.3333,7.0,0.5500,0.2500,1.0431,0.8750,0.9583,0.0,138.0,0.1353,3.0,2.0000,1.0000,4.0,4.0,79.0,1.0000,0.6667,0.7143,87.0,0.6667,1.0000,33.0,-0.1500,67.0,0.9375,0.5758,0.2341,47.0,1.0,1.3333,1.0000,0.0,0.5714,0.7293,0.6782,0.7500,0.8020,0.0,1.5000,2.0,0.6167,4,29,29,11.4286,0.0,...,3.5355,-999.0,1.6581,-999.0000,-999.0000,2.6667,17.3270,0.0,-999.0,0.2158,-999.0000,12.4291,-999.0,17.3270,-999.0000,1.0839,-999.0,2.6667,14.6444,-999.0,-999.0000,17.3270,2.6667,3.6775,1.0,2.6826,39.5025,-999.0,-999.0,0.2158,-999.0000,-999.0,750000.0,-999.0,39.5025,1.8969,0.0,-999.0,1.0000,-999.000000,19,0.000000,-999.000000,1.000000,6.000000,1.000000,12,24,-999.000000,34

In [37]:
#切分训练集测试集、oot
train_data,test_data = train_test_split(sample[sample['sample_type'] == 'train'],train_size=0.85,random_state=2023)
valid_data = sample[sample['sample_type'] == 'oot']

In [38]:
#分别统计oot和train的好坏样本情况
#将sample按照sample_type(oot/train)进行分组聚合（oot与train各为一组），再对分组后的数据对每组的label列进行聚合操作：
sample.groupby(["sample_type"],as_index =False).label.agg({"total":"count",  #统计每组总数，并将结果命名为total。
                                                           "good":lambda x:(x==0).sum(),   #统计每组label值为0的样本数量（未逾期），命名good。
                                                           "bad":lambda x:(x==1).sum(),     #统计每组label值为1的样本数量（逾期），命名 bad。
                                                           "nosure":lambda x:(x==2).sum(),    #统计每组label值为2的样本数量，命名nosure。
                                                           "bad_rate":lambda x:round((x==1).sum()/x.count(),4)})#计算坏样本率，命名bad_rate

  sample_type  total   good    bad  nosure  bad_rate
0         oot   2345   1564    781       0    0.3330
1       train  60568  40138  20430       0    0.3373

In [39]:
#样本预处理（重置索引）
train_data=train_data.reset_index(drop=True)
test_data=test_data.reset_index(drop=True)
valid_data=valid_data.reset_index(drop=True)

print('训练集：',train_data.shape)
print('测试集：',test_data.shape)
print('验证集：',valid_data.shape)

train_data.head(2)#查看前两行

训练集： (51482, 1691)
测试集： (9086, 1691)
验证集： (2345, 1691)

,app_order_id,label,sample_type,app_id_base_v3_install_mean_app_cnt_groupby_date_3d_7d_ratio,app_id_base_v3_install_day_cnt_15d,app_id_base_v3_update_day_cnt_15d_30d_ratio,app_id_base_v3_install_app_cnt_7d_15d_ratio,app_id_base_v3_install_var_app_cnt_groupby_date_60d_90d_ratio,app_id_base_v3_install_var_app_cnt_groupby_date_7d_15d_ratio,app_id_base_v3_install_app_cnt_60d_90d_ratio,app_id_base_v3_install_apply_last_days_diff_30d,app_id_base_v3_update_apply_first_days_diff_180d,app_id_base_v3_update_var_app_cnt_groupby_date_60d_90d_diff,app_id_base_v3_install_app_cnt_7d,app_id_base_v3_install_mean_app_cnt_groupby_date_3d,app_id_base_v3_install_avg_continuous_days_groupby_date_3d_7d_ratio,app_id_base_v3_install_mean_interval_day_groupby_date_7d,app_id_base_v3_install_first_last_days_diff_7d,app_id_base_v3_install_max_interval_day_groupby_date_180d,app_id_base_v3_install_time_density_7d,app_id_base_v3_install_app_cnt_3d_7d_ratio,app_id_base_v3_install_avg_continuous_days_groupby_date_7d_15d_ratio,app_id_base_v3_update_first_last_days_diff_90d,app_id_base_v3_update_day_cnt_30d_60d_ratio,app_id_base_v3_install_min_continuous_days_groupby_date_3d_7d_ratio,app_id_base_v3_install_day_cnt_infd,app_id_base_v3_update_mean_app_cnt_groupby_date_30d_60d_diff,app_id_base_v3_app_update_cnt,app_id_base_v3_update_day_cnt_60d_90d_ratio,app_id_base_v3_install_day_cnt_180d_infd_ratio,app_id_base_v3_update_time_density_180d,app_id_base_v3_update_day_cnt_infd,app_id_base_v3_install_max_app_cnt_groupby_date_3d_7d_ratio,app_id_base_v3_install_median_app_cnt_groupby_date_3d_7d_ratio,app_id_base_v3_install_median_continuous_days_groupby_date_7d_15d_ratio,app_id_base_v3_install_apply_last_days_diff_15d,app_id_base_v3_install_var_app_cnt_groupby_date_15d,app_id_base_v3_install_time_density_60d_90d_ratio,app_id_base_v3_update_apply_first_days_diff_60d_90d_ratio,app_id_base_v3_install_day_cnt_30d_60d_ratio,app_id_base_v3_update_mean_interval_day_groupby_date_30d_60d_ratio,app_id_base_v3_install_apply_last_days_diff_60d,app_id_base_v3_install_mean_app_cnt_groupby_date_7d,app_id_base_v3_install_app_cnt_3d,app_id_base_v3_update_app_cnt_30d_60d_ratio,app_id_comp_v1_seinst_updt_nonpreinst_iscomp_instdelmaxnull30_apply_start_diff_d7_0,app_id_comp_v1_seupdt_inst_iscomp_updt_end_start_diff_all_0,app_id_comp_v1_seupdt_inst_nonpreinst_iscomp_updt_end_start_diff_all_0,app_id_comp_v1_seinst_updt_iscomp_inst_day_avg_cnt_m6_0,app_id_comp_v1_up2in_updt_iscomp_up2in_time_diff_days_medium_d15_0,...,loan_id_base_v4_other_product_apply_overdue_days_std_in_inf_d,loan_id_base_v4_brush_order_third_loan_first_repay_time_diff,loan_id_base_v4_all_loan_success_inter_mean_rate_in_inf_d,loan_id_base_v4_self_app_pre_payoff_diff_mean_in_15_d,loan_id_base_v4_self_app_pre_payoff_diff_mean_in_15_orders,loan_id_base_v4_other_product_pre_payoff_overdue_days_mean_rate_in_15_orders,loan_id_base_v4_all_pre_payoff_inter_sum_in_15_orders,loan_id_base_v4_all_pre_payoff_overdue_days_mean_rate_in_15_d,loan_id_base_v4_other_app_pass_max_length_in_90_d,loan_id_base_v4_all_payoff_diff_mean_rate_in_15_orders,loan_id_base_v4_self_app_pre_payoff_diff_min_in_agg_180d,loan_id_base_v4_self_app_apply_diff_mean_in_15_orders,loan_id_base_v4_other_product_pre_payoff_diff_min_in_agg_90d,loan_id_base_v4_self_app_pre_payoff_inter_sum_in_7_orders,loan_id_base_v4_self_app_pre_payoff_diff_std_in_7_orders,loan_id_base_v4_all_pre_payoff_inter_mean_rate_in_30_d,loan_id_base_v4_other_product_pre_payoff_diff_range_in_7_orders,loan_id_base_v4_other_product_pre_payoff_overdue_days_mean_rate_in_90_d,loan_id_base_v4_all_payoff_inter_min_in_inf_d,loan_id_base_v4_self_app_pre_payoff_inter_mean_rate_in_7_d,loan_id_base_v4_all_pass_diff_mean_in_180_d,loan_id_base_v4_other_product_pre_payoff_inter_sum_in_7_orders,loan_id_base_v4_all_pre_payoff_overdue_days_mean_rate_in_30_d,loan_id_base_v4_brush_order_first_repay_early_day,loan_id_base_v4_all_loan_success_max_length_in_15_orders,loan_id_base_v4_self_app_payoff_diff_mean_in_agg_30d,loan_id_base_v4_self_app_pass_inter_min_in_15_orders,loan_id_base_v4_all_loan_success_amount_sum_min_in_agg_7d,loan_id_base_v4_other_product_pre_payoff_diff_sum_in_7_d,loan_id_base_v4_self_app_payoff_diff_mean_rate_in_3_orders,loan_id_base_v4_self_app_deny_diff_max_in_15_d,loan_id_base_v4_all_apply_amount_sum_max_in_agg_3d,loan_id_base_v4_other_product_pre_payoff_amount_mean_in_3_orders,loan_id_base_v4_all_pre_payoff_amount_sum_rate_in_7_d,loan_id_base_v4_other_product_loan_success_inter_mean_in_90_d,loan_id_base_v4_self_app_payoff_inter_std_in_3_orders,loan_id_base_v4_onloan_batch_pass_amount_sum,loan_id_base_v4_other_product_pre_payoff_diff_mean_in_15_d,loan_id_base_v4_all_pre_payoff_amount_mean_rate_in_90_d,fdc_id_query_v1_history_query_cnt_rto_d3_d30,fdc_id_query_v1_d3_records_num_max,fdc_id_query_v1_d3_records_num_std,fdc_id_query_v1_history_query_cnt_rto_d3_d99999,fdc_id_query_v1_history_query_cnt_rto_d90_d180,fdc_id_query_v1_history_query_cnt_rto_d7_d30,fdc_id_query_v1_history_query_cnt_rto_d180_d90,fdc_id_query_v1_history_query_cnt_diff_d30_d99999,fdc_id_query_v1_history_query_cnt_d30,fdc_id_query_v1_history_query_cnt_rto_d3_d7,fdc_id_query_v1_history_query_cnt_d90
0,1358810459561320448,0,train,-999.0,0.0,0.6250,-999.0,-999.0000,-999.0,1.0000,28.0,168.0,1.4883,0.0,-999.0,-999.0,-999.0,-999.0,44.0,-999.0,-999.00,-999.0,84.0,0.4000,-999.0,49.0,-1.0000,84.0,0.9091,0.3673,0.2184,60.0,-999.0,-999.0,-999.0,-999.0,-999.0000,1.0000,0.6818,0.3333,1.2602,28.0,-999.0,0.0,0.2667,168,344,344,17.8862,200.0,...,0.3333,1306977.0,1.5042,-999.0,-999.0,9.0,33.3093,0.0,3.0,0.7544,-999.0,4.8604,-999.0000,-999.0,-999.0,0.0000,-999.0000,9.0,7.3814,0.0,7.8083,-999.0000,0.0,0.3351,3.0,5.6186,53.5414,-999.0,-999.0,0.0,7.3047,1800000.0,-999.0,0.0,39.9845,0.0,0.0,-999.000,0.9816,4.5,71,0.0,9.0,1.166667,1.800000,0.857143,18,18,2.5,24
1,1336222654432718848,0,train,1.5,3.0,0.8333,0.8,1.3153,1.5,0.6818,0.0,137.0,4.1890,4.0,3.0,1.0,6.0,6.0,26.0,1.0,0.75,1.0,72.0,0.5714,1.0,47.0,1.9643,94.0,0.9130,0.6596,0.3577,30.0,1.0,1.5,1.0,0.0,1.3333,1.0522,0.8194,0.4545,0.8320,0.0,2.0,3.0,0.8333,0,9,9,6.8493,31.0,...,0.0000,6243.0,0.8785,-999.0,-999.0,1.0,35.7477,1.0,2.0,0.6085,-999.0,0.0025,3.8336,-999.0,-999.0,1.1215,3.8336,1.0,7.9489,0.0,7.4249,35.7477,1.0,1.4965,2.0,-999.0000,0.0025,1600000.0,-999.0,0.0,-999.0000,1600000.0,300000.0,0.0,7.0007,-999.0,600000.0,1.291,0.8108,6.5,14,0.0,8.0,1.000000,2.166667,1.000000,6,26,3.0,31

4.特征筛选

In [40]:
primaryKey=['app_order_id','sample_type'] #定义主键
target = ["label"]  #定义target

### 删除主键，只留target变量与特征变量x
feature_train_ = train_data.drop(primaryKey,axis=1)
feature_test_ = test_data.drop(primaryKey,axis=1)
feature_valid_ = valid_data.drop(primaryKey,axis=1)

### 分离x特征变量
x_train = feature_train_.drop('label',axis=1)
x_test = feature_test_.drop('label',axis=1)
x_valid = feature_valid_.drop('label',axis=1)

### 分离目标变量y标签target
y_train = feature_train_[['label']]
y_test = feature_test_[['label']]
y_valid = feature_valid_[['label']]

print(x_train.shape)   #shape返回x_train的行数和列数

(51482, 1688)

# 最终筛选加调参：手工

In [41]:
%%time
model = LGBMClassifier(
    #Boosting Parameters参数
    objective='binary',         #binary:logistic – 二分类逻辑回归，输出为概率
    #subsample=0.8,              #bagging_fraction，训练每个决策树所用到的子样本占总样本的比例；参考：0.8-1之间
    learning_rate=0.04,          #shrinkage rate 每次学习的步长. 越小模型越稳健  参考：[0.01, 0.02, 0.05, 0.1, 0.15,0.2]
    
    # other参数
    reg_alpha=0, 
    reg_lambda=0,  #L1 L2正则化项权重.可预防过拟合；
    #scale_pos_weight=1,         #正样本的权重 默认为1； trick如果要加强负样本权重，此值设置<1??;
    seed=23,                    #随机种子
    #is_unbalance=False,
    #sigmoid=1.0,                #sigmoid函数的参数,将用作于二分类;
    #subsample_for_bin=1000,     #构造分箱的样本数  默认50000;  手工1000 5000 10000 20000？？
    #subsample_freq=2,           #同一样本最大选择次数; 手工1 or 2？？
    #uniform_drop=False,         #only used in dart, true if want to use uniform drop
    #skip_drop=0.5,              #only used in dart, probability of skipping drop
    #xgboost_dart_mode=False,    #only used in dart, true if want to use xgboost dart mode
    #drop_rate=0.6,              #default=0.1, type=double,only used in dart
    verbose=-1,
    
    #Tree Parameters参数
    #max_bin=20,               #每个特征的最大分箱数. 默认255，手工加大？？
    max_depth=3,              #树的最大深度,一般5-8，推荐GBDT树的深度：6
    num_leaves=7,            #所有树最大叶子节点数. 默认=31
    #max_drop=5,               #最大叶子节点drop样本数  手工加大？？
    #colsample_bytree=0.8,     #构造每棵树时的子样本抽样比例.  0.7-0.8
    #min_child_samples=200,    #构建一个叶子节点所需的最少样本量，alias=min_data_per_leaf , min_data, min_data_in_leaf. default=20  手工减小？？
    #min_child_weight=3,       #一个叶子节点所需最小权重和，默认0.001
    #min_split_gain=3.5,       #在叶子节点做进一步划分的最小损失，默认0
    n_estimators=360,         #决策树的数量  1500-2000
    )
model.fit(x_train,y_train)
result,predprob_train,predprob_test,predprob_valid=getKSresult(model,x_train,y_train,x_test,y_test,x_valid,y_valid)
result

CPU times: user 5min 30s, sys: 233 ms, total: 5min 31s
Wall time: 15 s

   train_ks  test_ks  valid_ks  overfitting       loss
0  0.420497  0.36102  0.261234    14.144519  37.875015

In [49]:
### 变量特征重要性
feature_importance = get_feature_importance(model, x_train, importance_type='gain')
feature_importance = feature_importance.reset_index()
feature_importance.columns = ['imp','feature']
print('筛选前特征：',feature_importance.shape)
feature_importance_final = feature_importance[:680]
print('筛选后特征：',feature_importance_final.shape)
feature_importance_final.tail(10)

筛选前特征： (1688, 2)
筛选后特征： (680, 2)

           imp                                            feature
670  16.201500      loan_id_base_v4_all_deny_diff_mean_in_agg_15d
671  15.711300  app_id_base_v3_install_var_app_cnt_groupby_dat...
672  15.166580      fdc_id_base_v2_early_settle_trans_amt_min_d90
673  13.211100  fdc_id_base_v2_remain_amount_over90_heavy_over...
674  11.399600    loan_id_base_v4_self_app_deny_diff_mean_in_15_d
675   9.555700  loan_id_base_v4_self_app_pre_payoff_inter_max_...
676   1.583180  fdc_id_base_v2_large_trans_amount_over1m_earli...
677   1.410030  loan_id_base_v4_other_product_pre_payoff_amoun...
678   0.506312  sms_id_base_v2_all_phone_var_body_discnt_group...
679   0.094585  fdc_id_base_v2_install_loan_trans_amt_sum_rati...

In [50]:
feature_list_final = list(set(feature_importance_final.feature))
# feature_list_final = DF_columns

print(len(feature_list_final))

train_data_v1 = train_data[['label']+feature_list_final]
test_data_v1 = test_data[['label']+feature_list_final]
valid_data_v1 = valid_data[['label']+feature_list_final]

### x变量
x_train = train_data_v1.drop('label',axis=1)
x_test = test_data_v1.drop('label',axis=1)
x_valid = valid_data_v1.drop('label',axis=1)

### y标签
y_train = train_data_v1[['label']]
y_test = test_data_v1[['label']]
y_valid = valid_data_v1[['label']]
print(train_data_v1.shape)

680
(51482, 681)

In [51]:
%%time
model = LGBMClassifier(
    #Boosting Parameters参数
    objective='binary',          #binary:logistic – 二分类逻辑回归，输出为概率
    subsample=1,              #bagging_fraction，训练每个决策树所用到的子样本占总样本的比例；参考：0.8-1之间
    learning_rate=0.06,          #shrinkage rate 每次学习的步长. 越小模型越稳健  参考：[0.01, 0.02, 0.05, 0.1, 0.15,0.2]

    # other参数
    reg_alpha=10, 
    reg_lambda=10,                #L1 L2正则化项权重.可预防过拟合；
    scale_pos_weight=1,          #正样本的权重 默认为1； trick如果要加强负样本权重，此值设置<1??;
    seed=2024,                    #随机种子
    # is_unbalance=True,
    # sigmoid=1.0,                #sigmoid函数的参数,将用作于二分类;
    # subsample_for_bin=1000,     #构造分箱的样本数  默认50000;  手工1000 5000 10000 20000？？
    # subsample_freq=2,           #同一样本最大选择次数; 手工1 or 2？？
    # uniform_drop=False,         #only used in dart, true if want to use uniform drop
    # skip_drop=0.5,              #only used in dart, probability of skipping drop
    # xgboost_dart_mode=False,    #only used in dart, true if want to use xgboost dart mode
    # drop_rate=0.6,              #default=0.1, type=double,only used in dart
    verbose=-1,

    #Tree Parameters参数
    #max_bin=200,               #每个特征的最大分箱数. 默认255，手工加大？？
    max_depth=2,              #树的最大深度,一般5-8，推荐GBDT树的深度：6
    num_leaves=2,            #所有树最大叶子节点数. 默认=31
    #max_drop=5,               #最大叶子节点drop样本数  手工加大？？
    colsample_bytree=0.8,     #构造每棵树时的子样本抽样比例.  0.7-0.8
    min_child_samples = 100,    #构建一个叶子节点所需的最少样本量，alias=min_data_per_leaf , min_data, min_data_in_leaf. default=20  手工减小？？
    #min_child_weight=3,       #一个叶子节点所需最小权重和，默认0.001
    #min_split_gain=3.5,       #在叶子节点做进一步划分的最小损失，默认0
    n_estimators=480,         #决策树的数量  1500-2000
)
model.fit(x_train,y_train)
result,predprob_train,predprob_test,predprob_valid=getKSresult(model,x_train,y_train,x_test,y_test,x_valid,y_valid)
result

CPU times: user 1min 35s, sys: 0 ns, total: 1min 35s
Wall time: 4.45 s

   train_ks   test_ks  valid_ks  overfitting       loss
0   0.28603  0.277089  0.250907     3.126051  12.279542

In [57]:
### 变量特征重要性
feature_importance_v2 = get_feature_importance(model, x_train, importance_type='gain')
feature_importance_v2 = feature_importance_v2.reset_index()
feature_importance_v2.columns = ['imp','feature']
print(feature_importance_v2.shape)
feature_importance_final = feature_importance_v2[:125]   #筛选出前n个重要性最高的特征
print(feature_importance_final.shape)
feature_importance_final.tail(10)

(680, 2)
(125, 2)

           imp                                            feature
115  27.452101  app_id_gcate_v3_update_game_min_mininstalls_18...
116  26.760900         loan_id_base_v4_other_app_apply_cnt_in_7_d
117  26.649500  fdc_id_base_v2_remain_amount_over80_light_over...
118  26.330500  fdc_id_base_v2_tadpole_loan_trans_amt_max_rati...
119  25.820601  fdc_id_base_v2_loan_days_over60d_least_trans_p...
120  25.610100                  app_id_cate_v1_mininstalls_avg_y1
121  25.528000      fdc_id_base_v2_new_mob_plt_remain_amt_min_d30
122  25.475599  fdc_id_base_v2_large_trans_amount_over200k_ins...
123  25.455200  fdc_id_base_v2_large_trans_amount_over2m_least...
124  25.415800  fdc_id_base_v2_remain_amount_over90_loan_level...

In [58]:
feature_list_final = list(set(feature_importance_final.feature))
# feature_list_final = DF_columns

print(len(feature_list_final))

train_data_v1 = train_data[['label']+feature_list_final]
test_data_v1 = test_data[['label']+feature_list_final]
valid_data_v1 = valid_data[['label']+feature_list_final]

### x变量
x_train = train_data_v1.drop('label',axis=1)
x_test = test_data_v1.drop('label',axis=1)
x_valid = valid_data_v1.drop('label',axis=1)

### y标签
y_train = train_data_v1[['label']]
y_test = test_data_v1[['label']]
y_valid = valid_data_v1[['label']]
print(train_data_v1.shape)

125
(51482, 126)

In [59]:
%%time
model = LGBMClassifier(
    #Boosting Parameters参数
    objective='binary',          #binary:logistic – 二分类逻辑回归，输出为概率
    subsample=1,              #bagging_fraction，训练每个决策树所用到的子样本占总样本的比例；参考：0.8-1之间
    learning_rate=0.06,          #shrinkage rate 每次学习的步长. 越小模型越稳健  参考：[0.01, 0.02, 0.05, 0.1, 0.15,0.2]

    # other参数
    reg_alpha=10, 
    reg_lambda=10,                #L1 L2正则化项权重.可预防过拟合；
    scale_pos_weight=1,          #正样本的权重 默认为1； trick如果要加强负样本权重，此值设置<1??;
    seed=2024,                    #随机种子
    # is_unbalance=True,
    # sigmoid=1.0,                #sigmoid函数的参数,将用作于二分类;
    # subsample_for_bin=1000,     #构造分箱的样本数  默认50000;  手工1000 5000 10000 20000？？
    # subsample_freq=2,           #同一样本最大选择次数; 手工1 or 2？？
    # uniform_drop=False,         #only used in dart, true if want to use uniform drop
    # skip_drop=0.5,              #only used in dart, probability of skipping drop
    # xgboost_dart_mode=False,    #only used in dart, true if want to use xgboost dart mode
    # drop_rate=0.6,              #default=0.1, type=double,only used in dart
    verbose=-1,

    #Tree Parameters参数
    #max_bin=200,               #每个特征的最大分箱数. 默认255，手工加大？？
    max_depth=2,              #树的最大深度,一般5-8，推荐GBDT树的深度：6
    num_leaves=2,            #所有树最大叶子节点数. 默认=31
    #max_drop=5,               #最大叶子节点drop样本数  手工加大？？
    colsample_bytree=0.8,     #构造每棵树时的子样本抽样比例.  0.7-0.8
    min_child_samples = 100,    #构建一个叶子节点所需的最少样本量，alias=min_data_per_leaf , min_data, min_data_in_leaf. default=20  手工减小？？
    #min_child_weight=3,       #一个叶子节点所需最小权重和，默认0.001
    #min_split_gain=3.5,       #在叶子节点做进一步划分的最小损失，默认0
    n_estimators=480,         #决策树的数量  1500-2000
)
model.fit(x_train,y_train)
result,predprob_train,predprob_test,predprob_valid=getKSresult(model,x_train,y_train,x_test,y_test,x_valid,y_valid)
result

CPU times: user 25.3 s, sys: 0 ns, total: 25.3 s
Wall time: 1.07 s

   train_ks   test_ks  valid_ks  overfitting       loss
0  0.286048  0.275105  0.248353     3.825509  13.177994

### 网格调参

In [60]:
#第一次参数初始范围
max_depth_list =         [2]
num_leaves_list =        [2,3]
min_child_samples_list = [100]
reg_alpha_list  =    [0,10,20,30,40]
reg_lambda_list =    [0,10,20,30,40]
learning_rate_list = [0.03,0.04,0.05]
n_estimators_list =  [300,400,500]
print(f'max_depth_list:{len(max_depth_list)}  {max_depth_list},num_leaves_list:{len(num_leaves_list)} {num_leaves_list}')
print(f'min_child_samples_list:{len(min_child_samples_list)} {min_child_samples_list}')
print(f'max_depth_list:{len(reg_alpha_list)}  {reg_alpha_list},reg_lambda_list:{len(reg_lambda_list)} {reg_lambda_list}')
print(f'learning_rate_list:{len(learning_rate_list)}  {learning_rate_list},n_estimators_list:{len(n_estimators_list)} {n_estimators_list}')

total_times = len(max_depth_list)*len(num_leaves_list)*len(min_child_samples_list)*len(reg_alpha_list)*len(reg_lambda_list)*len(learning_rate_list)*len(n_estimators_list)
print('网格次数:',total_times)

one_times_s = 1.4#秒

print('网格总耗时(小时):',round(total_times*one_times_s/3600,2))

max_depth_list:1  [2],num_leaves_list:2 [2, 3]
min_child_samples_list:1 [100]
max_depth_list:5  [0, 10, 20, 30, 40],reg_lambda_list:5 [0, 10, 20, 30, 40]
learning_rate_list:3  [0.03, 0.04, 0.05],n_estimators_list:3 [300, 400, 500]
网格次数: 450
网格总耗时(小时): 0.17

In [61]:
%%time
#循环调参：max_depth num_leaves
ks_result=[]
i= 1
for max_depth in max_depth_list:
    for num_leaves in num_leaves_list:
        for min_child_samples in min_child_samples_list:
            for reg_alpha in reg_alpha_list:
                for reg_lambda in reg_lambda_list:
                    for learning_rate in learning_rate_list:
                        for n_estimators in n_estimators_list:
                            model = LGBMClassifier(
                                #Boosting Parameters参数
                                objective='binary',          #binary:logistic – 二分类逻辑回归，输出为概率
                                subsample=1,              #bagging_fraction，训练每个决策树所用到的子样本占总样本的比例；参考：0.8-1之间
                                learning_rate=learning_rate,          #shrinkage rate 每次学习的步长. 越小模型越稳健  参考：[0.01, 0.02, 0.05, 0.1, 0.15,0.2]

                                # other参数
                                reg_alpha=reg_alpha, 
                                reg_lambda=reg_lambda,                #L1 L2正则化项权重.可预防过拟合；
                                scale_pos_weight=1,          #正样本的权重 默认为1； trick如果要加强负样本权重，此值设置<1??;
                                seed=2024,                    #随机种子
                                # is_unbalance=True,
                                # sigmoid=1.0,                #sigmoid函数的参数,将用作于二分类;
                                # subsample_for_bin=1000,     #构造分箱的样本数  默认50000;  手工1000 5000 10000 20000？？
                                # subsample_freq=2,           #同一样本最大选择次数; 手工1 or 2？？
                                # uniform_drop=False,         #only used in dart, true if want to use uniform drop
                                # skip_drop=0.5,              #only used in dart, probability of skipping drop
                                # xgboost_dart_mode=False,    #only used in dart, true if want to use xgboost dart mode
                                # drop_rate=0.6,              #default=0.1, type=double,only used in dart
                                verbose=-1,

                                #Tree Parameters参bb
                                #max_bin=200,               #每个特征的最大分箱数. 默认255，手工加大？？
                                max_depth=max_depth,              #树的最大深度,一般5-8，推荐GBDT树的深度：6
                                num_leaves=num_leaves,            #所有树最大叶子节点数. 默认=31
                                #max_drop=5,               #最大叶子节点drop样本数  手工加大？？
                                colsample_bytree=0.8,     #构造每棵树时的子样本抽样比例.  0.7-0.8
                                min_child_samples = min_child_samples,    #构建一个叶子节点所需的最少样本量，alias=min_data_per_leaf , min_data, min_data_in_leaf. default=20  手工减小？？
                                #min_child_weight=3,       #一个叶子节点所需最小权重和，默认0.001
                                #min_split_gain=3.5,       #在叶子节点做进一步划分的最小损失，默认0
                                n_estimators=n_estimators,         #决策树的数量  1500-2000
                            )
                            model.fit(x_train,y_train)
                            result,predprob_train,predprob_test,predprob_valid=getKSresult(model,x_train,y_train,x_test,y_test,x_valid,y_valid)
                            result['max_depth']=max_depth
                            result['num_leaves']=num_leaves
                            result['min_child_samples']=min_child_samples
                            result['reg_alpha']=reg_alpha
                            result['reg_lambda']=reg_lambda
                            result['learning_rate']=learning_rate
                            result['n_estimators']=n_estimators
                            ks_result.append(result)
                            print(f"第{i}次，参数: max_depth:{max_depth},num_leaves:{num_leaves},min_child_samples:{min_child_samples},reg_alpha:{reg_alpha},reg_lambda:{reg_lambda},learning_rate:{learning_rate},n_estimators:{n_estimators}; 模型KS: train_ks:{result['train_ks'].iloc[0]},test_ks:{result['test_ks'].iloc[0]},valid_ks:{result['valid_ks'].iloc[0]}")
                            i= i+1
#将ks_result结果保存为df_ks_result
df_ks_result = pd.DataFrame()
for result in ks_result: 
    df_ks_result = pd.concat([df_ks_result,result])

第1次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24381835748494912,test_ks:0.24430672671375964,valid_ks:0.2598273902891892
第2次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.25429075178354743,test_ks:0.25086816906034004,valid_ks:0.256641920811079
第3次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.26173427609958827,test_ks:0.25507521597795974,valid_ks:0.26249136296504905
第4次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.25547636717129657,test_ks:0.25153488032646804,valid_ks:0.25918472939473625
第5次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.2655306257973721,test_ks:0.2571346467874704,valid_ks:0.26247335208647843
第6次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.2744953917133424,test_ks:0.26412941344612945,valid_ks:0.26436695036529334
第7次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.2619179532945565,test_ks:0.25418195972060464,valid_ks:0.25671068962016697
第8次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.2750701570010934,test_ks:0.26044691701155226,valid_ks:0.25990925791905584
第9次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:0,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.2831282266260924,test_ks:0.27253742553663796,valid_ks:0.25667630521562296
第10次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24402623745495122,test_ks:0.24587353620006508,valid_ks:0.2643833238912667
第11次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.25406861404381337,test_ks:0.2506872371545949,valid_ks:0.2579321546577769
第12次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.26123381994544614,test_ks:0.2558278318884121,valid_ks:0.26249136296504905
第13次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.2549401501684327,test_ks:0.25351600867256796,valid_ks:0.2572763949425453
第14次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26513509332997715,test_ks:0.256614657612976,valid_ks:0.2618241417816361
第15次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.2740547979443543,test_ks:0.2622288682177143,valid_ks:0.2618208670764414
第16次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.2619667401766903,test_ks:0.2533282348040006,valid_ks:0.25863376024573387
第17次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.27354388384266204,test_ks:0.25882461160457715,valid_ks:0.265660458917186
第18次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:10,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.2825498234979222,test_ks:0.26923275749346975,valid_ks:0.2579796378830996
第19次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24389009853269628,test_ks:0.24490425813357336,valid_ks:0.2611765688293911
第20次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.253622900976202,test_ks:0.25214837632620046,valid_ks:0.2572632961217666
第21次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.2613895249147794,test_ks:0.2543286818122383,valid_ks:0.2586501337717072
第22次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.2528392872024931,test_ks:0.2509206241086443,valid_ks:0.255356599022173
第23次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26325556156957847,test_ks:0.2553861451773285,valid_ks:0.26054864410831413
第24次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.2724434776112992,test_ks:0.2600440014231283,valid_ks:0.2605371826401328
第25次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.26076082307469084,test_ks:0.25486387534856,valid_ks:0.2579960114090729
第26次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.27332610273741886,test_ks:0.25868777234813123,valid_ks:0.2631045515127501
第27次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:20,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.28270599753944303,test_ks:0.2694288937610422,valid_ks:0.2586091999567739
第28次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24437557812303473,test_ks:0.2444336831350178,valid_ks:0.2623865723988198
第29次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.2536265826866819,test_ks:0.2520396651391351,valid_ks:0.2579239678947903
第30次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.26064145263948885,test_ks:0.253399695304589,valid_ks:0.25801893434543555
第31次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.2544999377315107,test_ks:0.251804757748903,valid_ks:0.25919946556811224
第32次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26407539176571654,test_ks:0.2557480089888187,valid_ks:0.2579910993512809
第33次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.27198866994263987,test_ks:0.26027434750481215,valid_ks:0.26181595501864946
第34次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.2611596424220194,test_ks:0.2539652975645653,valid_ks:0.25601399609000197
第35次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.2731344310675406,test_ks:0.25814269597662176,valid_ks:0.26247007738128375
第36次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:30,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.2806725358598601,test_ks:0.27040577400844756,valid_ks:0.2605289958771462
第37次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24352296349306324,test_ks:0.2437745740498034,valid_ks:0.2592584102616162
第38次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.25272461086378745,test_ks:0.2506849565003208,valid_ks:0.2579239678947903
第39次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.2608317744613452,test_ks:0.2544351123450295,valid_ks:0.25801893434543555
第40次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.2536082618744038,test_ks:0.25136915278255023,valid_ks:0.25726002141657195
第41次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26355897703333475,test_ks:0.2575786141528282,valid_ks:0.25671068962016697
第42次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.27168588553283374,test_ks:0.25954301770091803,valid_ks:0.26051917176156214
第43次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.26007620715491264,test_ks:0.2544351123450295,valid_ks:0.2567041402097776
第44次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.27177638946808613,test_ks:0.258249126509413,valid_ks:0.25800419817205955
第45次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:0,reg_lambda:40,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.28114198263031764,test_ks:0.26899252857659806,valid_ks:0.2579665390623209
第46次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24426191417034548,test_ks:0.24629317658649913,valid_ks:0.26238820975141713
第47次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.25339285650167936,test_ks:0.2515272781455544,valid_ks:0.25792233054219293
第48次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.26090061333584513,test_ks:0.25590385369754876,valid_ks:0.25929606937135485
第49次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.253911296006094,test_ks:0.25122547156328207,valid_ks:0.25727475758994794
第50次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26385008525775094,test_ks:0.2586816906034003,valid_ks:0.26055028146091147
第51次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.2718322461792349,test_ks:0.2608361486743317,valid_ks:0.2618339658972201
第52次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.26155238745324905,test_ks:0.2530750821795757,valid_ks:0.25674179931951624
第53次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.27205514658310137,test_ks:0.25826661152551444,valid_ks:0.26115692059822315
第54次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:0,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.28184317468380554,test_ks:0.26892030785791826,valid_ks:0.25926168496681085
第55次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.2438484253496383,test_ks:0.24348721161126705,valid_ks:0.2592534982038242
第56次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.2529250093011278,test_ks:0.2508719701507969,valid_ks:0.2578912208428436
第57次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.26041547120751224,test_ks:0.2555914040619973,valid_ks:0.25865832053469384
第58次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.25320574731811524,test_ks:0.25140336259666174,valid_ks:0.25856171673145123
第59次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26332673230653636,test_ks:0.25692710724852746,valid_ks:0.2617619223829375
第60次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.27134684083053767,test_ks:0.25986687060784,valid_ks:0.2624635279708944
第61次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.2604887105865638,test_ks:0.2538558261594086,valid_ks:0.25793379201037425
第62次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.2715400816987416,test_ks:0.25894472606301294,valid_ks:0.2605519188135088
第63次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:10,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.2805842321768834,test_ks:0.27004010910650045,valid_ks:0.25476469605823737
第64次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24374319457246635,test_ks:0.24342031241922682,valid_ks:0.2586157493671632
第65次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.2530745825858212,test_ks:0.2515310792360112,valid_ks:0.25663537140068965
第66次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.2612053044059822,test_ks:0.25544088087990685,valid_ks:0.2605764791024688
第67次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.25460444971461116,test_ks:0.2522464444599867,valid_ks:0.2578944955480383
第68次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26398345024232067,test_ks:0.2551322323348122,valid_ks:0.2599010711560692
第69次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.27133004534652444,test_ks:0.2600972166895239,valid_ks:0.26055846822389817
第70次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.25987599769629544,test_ks:0.2530408723654642,valid_ks:0.2592174764466829
第71次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.270372567772967,test_ks:0.2575504860834476,valid_ks:0.2592747837875895
第72次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:20,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.27962675460332603,test_ks:0.2685143513971288,valid_ks:0.25351703337907006
第73次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24478570582216724,test_ks:0.2440923452119944,valid_ks:0.25669431609419363
第74次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.253495974766697,test_ks:0.2506089346911842,valid_ks:0.2579092317214143
第75次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.2604982303897387,test_ks:0.25584075559596536,valid_ks:0.25993545556061315
第76次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.25359324144053946,test_ks:0.24994754495169574,valid_ks:0.257887946137649
第77次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26182039302876925,test_ks:0.2563630254247338,valid_ks:0.2586157493671632
第78次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.2702182565217165,test_ks:0.25856157614496444,valid_ks:0.2605568308713008
第79次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.26012728202944363,test_ks:0.25316782878672234,valid_ks:0.2534089681076461
第80次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.27020938127097216,test_ks:0.25891583777554106,valid_ks:0.2592682343772002
第81次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:30,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.2789289506683732,test_ks:0.2675830842352054,valid_ks:0.25348264897452605
第82次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.24434993775985753,test_ks:0.24404901278078656,valid_ks:0.25734516375163324
第83次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.2530356225972874,test_ks:0.2516732400190967,valid_ks:0.25983885175737054
第84次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.2598749718117987,test_ks:0.25391284251626106,valid_ks:0.2586599578872912
第85次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.25249990503819164,test_ks:0.2509403897790198,valid_ks:0.2591880040999309
第86次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.26114830369863484,test_ks:0.2567248892362241,valid_ks:0.25738282286137193
第87次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.04,n_estimators:500; 模型KS: train_ks:0.2699476693618542,test_ks:0.2581601809927232,valid_ks:0.2618356032498174
第88次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.05,n_estimators:300; 模型KS: train_ks:0.25917022965801306,test_ks:0.2526265535056697,valid_ks:0.25725510935878
第89次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.05,n_estimators:400; 模型KS: train_ks:0.26954885001452566,test_ks:0.25822860062094616,valid_ks:0.2611913050027671
第90次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:10,reg_lambda:40,learning_rate:0.05,n_estimators:500; 模型KS: train_ks:0.2785318928727133,test_ks:0.26765150386342834,valid_ks:0.255415543715677
第91次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:20,reg_lambda:0,learning_rate:0.03,n_estimators:300; 模型KS: train_ks:0.2437179962845163,test_ks:0.24519010013592699,valid_ks:0.2573320649308546
第92次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:20,reg_lambda:0,learning_rate:0.03,n_estimators:400; 模型KS: train_ks:0.2529396922729867,test_ks:0.2506165368720979,valid_ks:0.26047660059403155
第93次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:20,reg_lambda:0,learning_rate:0.03,n_estimators:500; 模型KS: train_ks:0.26039544958672645,test_ks:0.2542009651728888,valid_ks:0.2599370929132105
第94次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:20,reg_lambda:0,learning_rate:0.04,n_estimators:300; 模型KS: train_ks:0.2541701192404448,test_ks:0.25156680948630544,valid_ks:0.26112253619367914
第95次，参数: max_depth:2,num_leaves:2,min_child_samples:100,reg_alpha:20,reg_lambda:0,learning_rate:0.04,n_estimators:400; 模型KS: train_ks:0.2627068179770708,test_ks:0.25614788370487723,valid_ks:0.25735007580942526

In [62]:
#将ks_result结果保存为df_ks_result
df_ks_result = pd.DataFrame()
for result in ks_result: 
    df_ks_result = pd.concat([df_ks_result,result])

In [63]:
df_ks_result.sort_values(by = 'valid_ks',ascending=False)[:5]

,train_ks,test_ks,valid_ks,overfitting,loss,max_depth,num_leaves,min_child_samples,reg_alpha,reg_lambda,learning_rate,n_estimators
0,0.273544,0.258825,0.265660,5.380955,2.881960,2,2,100,0,10,0.05,400
0,0.268430,0.258189,0.264393,3.814998,1.503748,2,2,100,30,10,0.05,400
0,0.244026,0.245874,0.264383,-0.757008,-8.342171,2,2,100,0,10,0.03,300
0,0.274495,0.264129,0.264367,3.776376,3.689840,2,2,100,0,0,0.04,500
0,0.252433,0.249927,0.264287,0.992652,-4.695873,2,2,100,30,40,0.04,300

In [ ]:
# import lightgbm as lgb
# loaded_gbm = lgb.Booster(model_file='/home/mahaocheng/workspace/model_train/model_train_result/th_1_1010/train_result/score_th_3_1011.txt') 
# #loaded_gbm = lgb.Booster(model_file='/home/yutiangang/th_b7/model_train_result/score_th_b7_20250416_87feature_ol.txt') 
# DF_columns = loaded_gbm.feature_name()
# loaded_gbm.params

In [ ]:
# x_all = pd.concat([x_train,x_test,x_valid])
# y_all = pd.concat([y_train,y_test,y_valid])
# x_all.index=range(x_all.shape[0])
# y_all.index=range(y_all.shape[0])

In [64]:
##更新参数重新跑
model = LGBMClassifier(
    #Boosting Parameters参数
    objective='binary',          #binary:logistic – 二分类逻辑回归，输出为概率
    subsample=1,              #bagging_fraction，训练每个决策树所用到的子样本占总样本的比例；参考：0.8-1之间
    learning_rate=0.05,          #shrinkage rate 每次学习的步长. 越小模型越稳健  参考：[0.01, 0.02, 0.05, 0.1, 0.15,0.2]

    # other参数
    reg_alpha=0, 
    reg_lambda=10,                #L1 L2正则化项权重.可预防过拟合；
    scale_pos_weight=1,          #正样本的权重 默认为1； trick如果要加强负样本权重，此值设置<1??;
    seed=2024,                    #随机种子
    # is_unbalance=True,
    # sigmoid=1.0,                #sigmoid函数的参数,将用作于二分类;
    # subsample_for_bin=1000,     #构造分箱的样本数  默认50000;  手工1000 5000 10000 20000？？
    # subsample_freq=2,           #同一样本最大选择次数; 手工1 or 2？？
    # uniform_drop=False,         #only used in dart, true if want to use uniform drop
    # skip_drop=0.5,              #only used in dart, probability of skipping drop
    # xgboost_dart_mode=False,    #only used in dart, true if want to use xgboost dart mode
    # drop_rate=0.6,              #default=0.1, type=double,only used in dart
    verbose=-1,

    #Tree Parameters参数
    #max_bin=200,               #每个特征的最大分箱数. 默认255，手工加大？？
    max_depth=2,              #树的最大深度,一般5-8，推荐GBDT树的深度：6
    num_leaves=2,            #所有树最大叶子节点数. 默认=31
    #max_drop=5,               #最大叶子节点drop样本数  手工加大？？
    colsample_bytree=0.8,     #构造每棵树时的子样本抽样比例.  0.7-0.8
    min_child_samples = 100,    #构建一个叶子节点所需的最少样本量，alias=min_data_per_leaf , min_data, min_data_in_leaf. default=20  手工减小？？
    #min_child_weight=3,       #一个叶子节点所需最小权重和，默认0.001
    #min_split_gain=3.5,       #在叶子节点做进一步划分的最小损失，默认0
    n_estimators=400,         #决策树的数量  1500-2000
)
model.fit(x_train,y_train)
#model.fit(x_all,y_all)
result,predprob_train,predprob_test,predprob_valid=getKSresult(model,x_train,y_train,x_test,y_test,x_valid,y_valid)
result

   train_ks   test_ks  valid_ks  overfitting     loss
0  0.273544  0.258825   0.26566     5.380955  2.88196

### 保存入模变量

In [67]:
###入模变量及保存:
feature_importance_final = get_feature_importance(model, x_train, importance_type='gain')
feature_importance_final = feature_importance_final.reset_index()
feature_importance_final.columns = ['imp','feature']
print(feature_importance_final.shape)
columns=feature_importance_final.feature.to_list()

###入模变量保存
df_in_var = feature_importance_final
df_in_var.to_csv('/home/zengjunyao/notebook/to_zjy_模型训练/model_train_result/model_in_var_{}.csv'.format(datetime.now().strftime('%Y%m%d')),index=False)
print(df_in_var.shape)
#df_in_var.head(100)

(125, 2)
(125, 2)

In [68]:
df_in_var

             imp                                            feature
0    5711.687012  loan_id_base_v4_other_product_pre_payoff_amoun...
1    4705.933937  loan_id_base_v4_all_pre_payoff_amount_mean_rat...
2    3461.462936  fdc_id_base_v2_plt_agg_trans_amount_plt_sum_am...
3    2974.623047  fdc_id_base_v2_loan_days_over180d_heavy_overdu...
4    2745.837021  loan_id_base_v4_all_deny_pre_payoff_cnt_rate_i...
..           ...                                                ...
120     0.000000  app_id_comp_v1_seinst_updt_nonpreinst_iscomp_i...
121     0.000000  fdc_id_query_v1_history_query_cnt_diff_d30_d99999
122     0.000000  loan_id_base_v4_all_apply_amount_sum_max_in_ag...
123     0.000000                  app_id_cate_v1_mininstalls_avg_y1
124     0.000000         app_id_gcate_v3_update_other_var_score_30d

[125 rows x 2 columns]

In [ ]:
#循环获取模型初筛后特征的Iv和Woe, 每个特征耗时0.5s
import math
save_interval = 100
col_list = feature_importance_final.feature.to_list()[:500]
loop_times = math.ceil(len(col_list)/save_interval)
print("特征数量: ",len(col_list))
print("保存间隔: ",save_interval)
print("循环次数: ",loop_times)

特征数量:  50
保存间隔:  100
循环次数:  1

In [ ]:
#保存：计算筛选后的变量train_woe, valid_woe
train_woe_result,valid_woe_result=saveTrainValidWoe(
    train_woes =train_woes,
    valid_woes = valid_woes,
    variables = iv_csi['feature'].to_list(),
    header=None,
    processMiss=True,
    addVar=True,
)
#合并 保存
woe_result = pd.concat([train_woe_result.reset_index(drop=True),emptyData(len(train_woe_result)),valid_woe_result.reset_index(drop=True)],axis=1)
woe_result.columns = ['variable_name', 'variable_cut', 'bad', 'good', 'badRate', 'Total',
       'good_pct', 'bad_pct', 'Total_pct', 'Odds', 'WOE', 'IV', 'space',
       'variable_name_oot', 'variable_cut_oot', 'bad_oot', 'good_oot', 'badRate_oot', 'Total_oot',
       'good_pct_oot', 'bad_pct_oot', 'Total_pct_oot', 'Odds_oot', 'WOE_oot', 'IV_oot']
woe_result.to_csv('model_train_result/all_feature_woe_{}_inmodel.csv'.format(datetime.now().strftime('%Y%m%d')),index = False,encoding='utf_8_sig')

# 样本打分

## 计算auc

In [69]:
#定义概率转分数的函数p2score
def p2score(prob):
    """
    概率转模型分
    """
    return round(550 - 60 / np.log(2) * np.log(prob / (1 - prob)), 0)

In [70]:
#类别预测：计算各数据集中每个样本的预测类别(0/1)，储存在predprob中
pred_train = pd.DataFrame(model.predict(x_train),columns=['predprob'])
pred_test = pd.DataFrame(model.predict(x_test),columns=['predprob'])
pred_valid = pd.DataFrame(model.predict(x_valid),columns=['predprob'])

In [71]:
#重置索引
x_train.index = range(x_train.shape[0])   #.shape[0]:返回行数 ; range(n):(0,n-1)
x_test.index = range(x_test.shape[0])
x_valid.index = range(x_valid.shape[0])
#x_valid = x_valid.reset_index(drop=True)  重置索引

train_data.index = range(train_data.shape[0])
test_data.index = range(test_data.shape[0])
valid_data.index = range(valid_data.shape[0])

In [72]:
#计算快，保存慢
#概率预测：预测样本为正类1的概率
pred_train = pd.DataFrame(model.predict_proba(x_train)[:,1],columns=['predprob'])  #model.predict_proba()：返回[属于类别0的概率,属于类别1的概率]
pred_test = pd.DataFrame(model.predict_proba(x_test)[:,1],columns=['predprob'])
pred_valid = pd.DataFrame(model.predict_proba(x_valid)[:,1],columns=['predprob'])
test_data['sample_type'] = 'test'

In [73]:
#将预测概率值与原始数据合并
try:
    train_data.drop(['predprob'], axis=1, inplace=True)
    test_data.drop(['predprob'], axis=1, inplace=True)
    valid_data.drop(['predprob'], axis=1, inplace=True)
except:
    pass
# 保留主键 target predprob score 将预测结果与原始数据合并
pred_train = train_data[["app_order_id",'sample_type',"label"] + df_in_var.feature.to_list()].join(pred_train)
pred_test = test_data[["app_order_id",'sample_type',"label"]+ df_in_var.feature.to_list()].join(pred_test)
pred_valid = valid_data[["app_order_id",'sample_type',"label"]+ df_in_var.feature.to_list()].join(pred_valid)
#按行拼接训练集、测试集、验证集的结果
pred_all = pd.concat([pred_train,pred_test,pred_valid],axis=0)  
# pred_all["apply_month"] = pred_all["date"].apply(lambda x: x[0:7]) 获取年月
# pred_all = pred_all.reset_index(drop=True)  重置索引
## 保存带概率的样本：
pred_all.to_pickle('/home/zengjunyao/notebook/to_zjy_模型训练/model_train_result/sample_data_with_pred_var_{}.pkl'.format(datetime.now().strftime('%Y%m%d')))
print(pred_all.shape)

(62913, 129)

,app_order_id,sample_type,label,loan_id_base_v4_other_product_pre_payoff_amount_sum_rate_in_90_d,loan_id_base_v4_all_pre_payoff_amount_mean_rate_in_3_orders,fdc_id_base_v2_plt_agg_trans_amount_plt_sum_amt_avg_d60,fdc_id_base_v2_loan_days_over180d_heavy_overdue_plt_cnt_ratio_d360,loan_id_base_v4_all_deny_pre_payoff_cnt_rate_in_30_d,loan_id_base_v4_all_pre_payoff_amount_sum_rate_in_15_d,loan_id_base_v4_all_payoff_inter_min_in_inf_d,loan_id_base_v4_other_product_pre_payoff_onloan_cnt_rate_in_90_d,fdc_id_base_v2_plt_agg_trans_amount_plt_sum_amt_std_d720,fdc_id_base_v2_cur_on_loan_cur_ovd_days_median_d360,loan_id_base_v4_other_product_pre_payoff_diff_range_in_7_orders,fdc_id_base_v2_large_trans_amount_over1m_old_mob_plt_plt_cnt_ratio_d30,loan_id_base_v4_brush_order_first_repay_early_day,loan_id_base_v4_all_payoff_pre_payoff_cnt_rate_in_180_d,fdc_id_base_v2_remain_amount_over70_light_overdue_plt_cnt_d720,fdc_id_base_v2_loan_quality_2_cur_ovd_days_avg_d360,fdc_id_base_v2_loan_days_over120d_old_mob_plt_plt_cnt_ratio_d30,fdc_id_base_v2_cur_on_loan_hist_ovd_days_median_d99999,ui_id_base_v2_user_education_level,app_id_gcate_v3_update_finance_mean_mininstalls_30d_60d_diff,fdc_id_base_v2_cash_loan_cur_ovd_days_sum_d180,loan_id_base_v4_all_pre_payoff_amount_mean_rate_in_15_d,fdc_id_base_v2_loan_days_over120d_early_settle_plt_cnt_ratio_d270,app_id_gcate_v3_update_other_var_ratings_infd,sms_id_base_v2_all_phone_max_body_discnt_groupby_phone_180d,app_id_base_v3_install_mean_app_cnt_groupby_date_3d,loan_id_base_v4_other_product_pre_payoff_amount_mean_rate_in_3_orders,fdc_id_base_v2_on_loan_remain_days_sum_d3,app_id_gcate_v3_update_other_var_score_90d,loan_id_base_v4_other_product_pre_payoff_cnt_in_7_orders,sms_id_loan_v1_repy_cnt,loan_id_base_v4_all_onloan_inter_max_in_7_orders,app_id_base_v3_install_mean_app_cnt_groupby_date_7d,app_id_base_v3_app_update_cnt,fdc_id_base_v2_loan_days_over120d_loan_quality_1_plt_cnt_ratio_d60,loan_id_base_v4_all_pre_payoff_overdue_days_mean_rate_in_7_orders,loan_id_base_v4_all_loan_success_amount_mean_in_3_d,fdc_id_base_v2_earliest_trans_plt_trans_amt_sum_d30,loan_id_base_v4_other_product_pre_payoff_cnt_in_15_orders,fdc_id_base_v2_cash_loan_remain_amt_median_d60,sms_id_base_v2_letter_phone_mean_word_discnt_groupby_phone_15d,loan_id_base_v4_all_pass_amount_mean_rate_in_15_orders,fdc_id_base_v2_loan_level_3_loan_cnt_ratio_d180,fdc_id_base_v2_large_trans_amount_over1m_early_settle_plt_cnt_ratio_d360,fdc_id_base_v2_loan_days_over180d_earliest_trans_plt_plt_cnt_ratio_d3,fdc_id_base_v2_light_overdue_remain_days_std_d99999,loan_id_base_v4_all_apply_amount_sum_range_in_agg_infd,...,app_id_comp_v1_seupdt_updt_nonpreinst_iscomp_updt_end_start_diff_m6_0,fdc_id_query_v1_history_query_cnt_rto_d3_d7,fdc_id_base_v2_loan_days_over180d_cur_on_loan_plt_plt_cnt_ratio_d99999,app_id_gcate_v3_update_life_var_ratings_15d_30d_diff,app_id_base_v3_install_app_cnt_3d,sms_id_base_v2_all_phone_var_body_discnt_groupby_phone_type_infd,loan_id_base_v4_self_product_deny_inter_mean_rate_in_inf_d,fdc_id_base_v2_most_trans_hist_ovd_days_max_d270,app_id_gcate_v3_update_finance_mean_mininstalls_30d_60d_ratio,loan_id_base_v4_other_app_loan_success_order_cnt_mean_in_agg_15d,app_id_cate_v1_cate_finance_reviews_avg_y1,sms_id_base_v2_digit_phone_word_discnt_ratio_180d,fdc_id_base_v2_loan_days_over60d_loan_level_3_plt_cnt_ratio_d720,sms_id_base_v2_digit_phone_max_body_discnt_groupby_date_180d,fdc_id_base_v2_loan_days_over180d_old_mob_plt_loan_cnt_ratio_d720,loan_id_base_v4_all_payoff_pre_payoff_cnt_rate_in_15_d,fdc_id_base_v2_heavy_overdue_remain_amt_sum_ratio_d99999,fdc_id_base_v2_hist_ovd_days_std_d360,fdc_id_base_v2_remain_amount_over90_light_overdue_loan_cnt_d99999,fdc_id_base_v2_new_mob_plt_remain_amt_min_d30,fdc_id_base_v2_light_overdue_trans_amt_max_ratio_d720,loan_id_base_v4_all_payoff_diff_mean_in_90_d,fdc_id_base_v2_remain_amount_over90_loan_level_3_loan_cnt_ratio_d270,fdc_id_base_v2_on_loan_remain_days_std_d720,fdc_id_base_v2_large_trans_amount_over2m_least_trans_plt_loan_cnt_ratio_d90,loan_id_base_v4_other_app_apply_cnt_in_7_d,loan_id_base_v4_all_pass_inter_min_in_inf_d,fdc_id_base_v2_tadpole_loan_trans_amt_max_ratio_d270,app_id_loan_v3_install_first_last_days_diff_180d,loan_id_base_v4_all_pre_payoff_diff_max_in_agg_30d,app_id_gcate_v3_update_finance_median_score_90d_180d_ratio,sms_id_base_v2_letter_phone_word_discnt_ratio_60d_90d_diff,fdc_id_base_v2_cur_on_loan_hist_ovd_days_min_d99999,fdc_id_base_v2_old_mob_plt_trans_amt_avg_ratio_d180,fdc_id_base_v2_large_trans_amount_over200k_loan_quality_1_loan_cnt_ratio_d99999,fdc_id_base_v2_remain_amount_over80_light_overdue_plt_cnt_ratio_d720,app_id_gcate_v3_update_game_min_mininstalls_180d_infd_ratio,app_id_cashloan_v2_install_app_cnt_ratio_180d_infd_diff,loan_id_base_v4_self_app_pass_inter_mean_rate_in_15_orders,loan_id_base_v4_all_pass_amount_sum_mean_in_agg_180d,fdc_id_base_v2_large_trans_amount_over200k_install_loan_cnt_ratio_d180,fdc_id_query_v1_history_query_cnt_d30,fdc_id_base_v2_loan_days_over60d_least_trans_plt_plt_cnt_ratio_d99999,loan_id_base_v4_other_product_payoff_overdue_days_mean_rate_in_7_orders,app_id_comp_v1_seinst_updt_nonpreinst_iscomp_instdelmaxnull30_day_avg_cnt_d15_0,fdc_id_query_v1_history_query_cnt_diff_d30_d99999,loan_id_base_v4_all_apply_amount_sum_max_in_agg_3d,app_id_cate_v1_mininstalls_avg_y1,app_id_gcate_v3_update_other_var_score_30d,predprob
0,1358810459561320448,train,0,0.0719,0.0000,1.477256e+06,0.000000,10.0000,0.0000,7.3814,0.5000,5.675335e+06,1.0,-999.0000,0.166667,0.3351,5.0000,2,1.333333,0.666667,1.0,5,-5.408333e+05,2,0.0000,0.625000,1.935685e+15,87.0,-999.0000,0.0000,-999,0.0805,0.0,0,0.0768,-999.0000,84.0,0.666667,0.0000,-9.990000e+02,531915.0,1.0,116666.0,34.0000,0.4657,0.000000,0.250000,-999.0,80.674579,7000000.0,...,163,2.500000,1.000000,-9.990000e+02,0.0,108112.5,1.0000,-999,0.9144,-999.0,101049.3171,2.0016,0.000000,11.0,0.098592,9.0000,-999.000000,0.330719,12,-999.0,1.000000,2.8809,0.000000,82.627477,0.000000,0.0,27.5834,0.907000,140.0,-999.0000,1.0209,1.6667,1,1.000000,0.492958,0.250000,5.0,0.2721,3.7622,7.117647e+05,0.087719,18,0.125000,-999.0000,100.0000,18,1800000.0,2.094765e+08,0.0509,0.384255
1,1336222654432718848,train,0,0.4054,0.4737,1.750000e+06,0.000000,1.0000,0.4054,7.9489,4.0000,1.011003e+06,-999.0,3.8336,0.000000,1.4965,0.8000,1,-999.000000,0.000000,-999.0,3,0.000000e+00,-999,0.8108,0.600000,1.730485e+15,101.0,3.0000,0.4737,-999,0.0823,4.0,0,-999.0000,2.0000,94.0,0.500000,1.0000,8.000000e+05,1000000.0,4.0,700000.0,27.8571,1.1532,0.000000,0.200000,-999.0,0.000000,1300000.0,...,9,3.000000,0.200000,8.208510e+13,3.0,38920.5,-999.0000,-999,1.0000,1.0,585.5000,1.3694,0.000000,15.0,0.214286,0.8000,-999.000000,0.000000,1,-999.0,0.600000,1.2910,0.000000,30.646166,0.000000,0.0,0.0025,0.800000,77.0,3.8336,1.0000,0.7091,-999,0.868087,0.571429,0.200000,1.0,0.0884,2.0000,5.333333e+05,0.000000,26,0.000000,1.0000,11.7647,6,1600000.0,7.457758e+08,0.0770,0.325704
2,1368767198008238080,train,1,0.3333,1.0000,1.328967e+06,0.000000,1.0000,0.0000,22.7689,0.5000,1.548042e+06,1.0,-999.0000,0.000000,1.5719,0.5000,3,1.000000,0.000000,1.0,3,6.863636e+05,1,0.0000,0.571429,2.125195e+15,32.0,2.5000,1.0000,-999,0.1096,1.0,0,1.0082,2.6667,62.0,0.625000,2.0000,-9.990000e+02,230734.0,1.0,500000.0,30.0000,1.0000,0.000000,0.285714,-999.0,70.054889,0.0,...,56,2.000000,0.714286,0.000000e+00,5.0,15488.0,-999.0000,-999,1.0498,-999.0,141144.6471,0.2185,0.000000,58.0,0.097561,0.0000,-999.000000,0.000000,4,230734.0,0.583333,-999.0000,0.000000,91.197063,0.045455,0.0,19.7979,0.583333,169.0,-999.0000,1.0000,0.0000,1,0.944470,0.585366,0.214286,1.0,0.1967,0.0000,1.000000e+06,0.074074,31,0.000000,2.0000,14.2857,4,1000000.0,4.823595e+08,0.0836,0.327328
3,1376421856231088128,train,0,0.2273,0.8824,9.228021e+06,0.045455,1.3333,0.3704,3.9941,0.3333,1.731597e+07,19.0,-999.0000,0.727273,1.7115,0.6667,0,16.103448,0.636364,19.0,5,0.000000e+00,-999,0.9259,0.772727,1.479085e+15,18.0,7.0000,0.0000,91,0.1115,1.0,1,3.9941,5.0000,124.0,0.846154,2.0000,-9.990000e+02,6000000.0,1.0,1101523.0,20.5821,0.9259,0.000000,0.727273,1.0,-999.000000,1400000.0,...,65,2.250000,0.434783,1.691739e+15,28.0,9248.0,1.0000,-999,1.0000,1.0,152862.8462,4.6199,0.000000,9.0,0.103306,0.6667,0.061554,3.447586,0,800000.0,-999.000000,4.7372,0.000000,95.323888,0.000000,1.0,8.8557,0.932345,177.0,4.7372,1.0000,0.2102,12,1.003022,0.232713,0.000000,1.0,0.2075,0.0000,1.000000e+06,0.225610,29,0.000000,3.0000,1100.0000,8,1000000.0,1.033889e+08,0.0997,0.310855
4,1298632098202693632,train,0,0.5169,0.0000,8.090000e+06,0.230769,1.3333,0.5476,3.9223,8.0000,1.231825e+08,91.0,0.0000,1.000000,1.4821,0.9231,2,3.857143,1.000000,91.0,1,8.062500e+05,44,0.8762,0.857143,2.341075e+15,109.0,1.5000,0.0000,-999,0.0980,3.0,1,-999.0000,1.6000,118.0,1.000000,1.0000,1.266667e+06,8200000.0,8.0,2172000.0,23.5833,0.8621,0.000000,0.769231,-999.0,112.109589,3600000.0,...,83,1.000000,0.294118,3.423440e+14,3.0,142044.5,0.7832,-999,1.0754,-999.0,33141.5833,1.9708,0.000000,24.0,0.047059,0.8333,0.534788,63.635695,5,-999.0,0.214286,7.4999,0.000000,114.611171,0.000000,0.0,84.3925,0.418605,129.0,-999.0000,1.0118,0.9937,3,1.000000,0.941176,0.117647,1.0,0.1775,2.2954,3.400000e+06,0.437500,8,0.117647,1.0000,16.6667,23,3800000.0,2.670692e+08,0.0877,0.249673
5,1310068257420128256,train,0,-999.0000,-999.0000,7.250000e+05,0.000000,0.0000,-999.0000,-999.0000,0.0000,1.010775e+06,1.0,-999.0000,0.000000,-999.0000,0.0000,1,1.000000,1.000000,1.0,3,0.000000e+00,1,-999.0000,0.333333,3.454370e+15,110.0,1.0000,-999.0000,-999,0.0968,0.0,0,-999.0000,1.5000,193.0,0.500000,-999.0000,-9.990000e+02,450000.0,0.0,612500.0,18.6000,-999.0000,0.000000,0.000000,-999.0,84.500000,-999.0,...,17,1.000000,1.000000,-1.652832e+14,1.0,129032.0,-999.0000,1,1.0000,-999.0,51.0000,1.4337,0.000000,17.0,0.000000,0.0000,-999.000000,0.000000,2,-999.0,0.225000,-999.0000,0.000000,20.885934,0.000000,0.0,-999.0000,0.500000,129.0,-999.0000,1.0000,0.8351,1,0.815686,0.550000,0.333333,1.0,0.2379,-999.0000,-9.990000e+02,0.250000,4,0.000000,-999.0000,100.0000,19,-999.0,2.846111e+09,0.0779,0.104122
6,1373169444145913856,train,0,0.1613,0.0000,8.094320e+06,0.000000,1.6000,0.4074,5.1611,0.4000,1.747672e+07,-999.0,0.0000,0.333333,0.2006,0.8000,0,-999.000000,0.555556,6.0,5,-3.372500e+05,-999,1.0185,0.461538,2.409109e+15,242.0,1.0000,0.0000,96,0.1110,2.0,0,1.1570,1.0000,69.0,0.700000,2.3333,-9.990000e+02,9000000.0,2.0,1277000.0,36.0000,0.9459,0.000000,0.461538,1.0,-999.000000,2400000.0,...,25,1.833333,0.615385,1.149835e+15,1.0,27378.0,1.0000,-999,0.9452,1.0,64.0000,2.7837,0.000000,79.0,0.022727,0.8000,-999.000000,0.000000,0,760000.0,-999.000000,2.9453,0.000000,68.381739,0.000000,0.0,10.2062,1.000000,128.0,8.8292,1.0000,0.9436,6,1.042191,0.886364,0.000000,1.0,0.3368,3.2491,1.000000e+06,0.172414,26,0.076923,3.0000,100.0000,11,2400000.0,2.290909e+07,0.1103,0.290306
7,1382369201246494720,train,0,-999.0000,1.0000,4.440123e+06,0.000000,0.0000,-999.0000,240.3688,0.0000,5.023457e+06,-999.0,-999.0000,0.888889,2.1782,0.0000,0,-999.000000,0.555556,-999.0,5,5.757792e+05,-999,-999.0000,0.700000,1.857101e+15,11.0,1.5000,1.0000,148,0.1978,1.0,0,-999.0000,1.3333,71.0,0.555556,1.0000,-9.990000e+02,2100000.0,1.0,1850000.0,32.0000,0.0000,0.000000,0.700000,0.5,-999.000000,0.0,...,11,1.444444,0.900000,1.815291e+15,6.0,50.0,-999.0000,-999,1.0472,-999.0,433.5556,3.0923,0.000000,3.0,0.078431,0.0000,-999.000000,-999.000000,0,-999.0,-999.000000,-999.0000,0.000000,102.179715,0.000000,0.0,-999.0000,1.000000,11.0,-999.0000,1.0000,2.6000,-999,1.034424,1.000000,0.000000,1.0,0.3922,0.0000,-9.990000e+02,0.000000,17,0.000000,1.0000,83.3333,13,-999.0,8.660604e+07,0.1413,0.307049
8,1396004566935068672,train,1,0.7774,1.1087,-9.990000e+02,0.000000,1.2222,0.4189,3.1313,3.7500,0.000000e+00,-999.0,11.5378,-999.000000,0.4200,0.9500,0,-999.000000,-999.000000,423.0,5,0.000000e+00,-999,1.0473,0.000000,2.634703e+15,85.0,4.0000,1.1087,-999,0.1436,3.0,0,8.2346,4.0000,43.0,-999.000000,1.7500,-9.990000e+02,-999.0,10.0,-999.0,30.7778,0.5286,0.000000,0.000000,-999.0,-999.000000,3200000.0,...,0,-999.000000,0.750000,0.000000e+00,4.0,31250.0,1.0000,-999,1.0000,-999.0,-999.0000,3.1802,0.000000,7.0,0.000000,0.6667,1.000000,-999.000000,0,-999.0,-999.000000,2.8381,0.000000,-999.000000,-999.000000,3.0,32.2440,-999.000000,180.0,12.8883,1.0229,0.7109,91,1.000000,0.266667,0.000000,1.0,0.0771,0.0000,9.000000e+05,0.000000,10,0.125000,2.0000,100.0000,23,800000.0,7.885631e+08,0.1425,0.293013
9,1296659500564656128,train,1,0.2449,0.0000,-9.990000e+02,0.333333,2.2500,0.2609,6.7921,0.7500,1.192920e+06,35.0,0.0000,-999.000000,-0.5555,1.0000,0,8.000000,-999.000000,35.0,3,-1.500000e+07,43,0.8696,0.333333,2.383114e+15,38.0,1.0000,0.0000,-999,0.0806,2.0,0,2.5460,1.0000,66.0,-999.000000,2.5000,3.000000e+05,-999.0,3.0,-999.0,27.8462,0.6735,0.000000,0.000000,-999.0,-999.000000,900000.0,...,0,-999.000000,0.666667,-1.716291e+15,1.0,968.0,-999.0000,35,0.4000,-999.0,690.8000,2.2717,0.000000,17.0,0.166667,1.0000,0.758696,13.500000,0,-999.0,-999.000000,2.0202,0.000000,38.177946,-999.000000,0.0,14.5093,0.315559,145.0,-999.0000,1.0000,0.0000,35,1.000000,0.500000,0.000000,-999.0,0.0708,2.6354,3.000000e+05,0.000000,0,0.000000,2.5000,100.0000,20,1000000.0,5.375000e+08,0.0681,0.594900
10,1423029543839088640,train,0,0.4054,0.8108,8.480000e+05,0.000000,0.5000,0.4054,10.7620,1.0000,5.188603e+05,-999.0,-999.0000,0.000000,1.1484,0.5000,0,-999.000000,0.000000,-999.0,4,0.000000e+00,-999,0.8108,0.400000,4.300229e+15,7.0,2.0000,0.8108,-999,0.0540,1.0,0,-999.0000,2.0000,27.0,0.800000,1.0000,1.100000e+06,1540000.0,1.0,476426.0,17.7000,0.0000,0.000000,0.200000,-999.0,-999.000000,350000.0,...,7,2.666667,0.428571,0.000000e+00,4.0,98.0,-999.0000,-999,1.0000,-999.0,1495.2500,7.4667,0.000000,7.0,0.000000,0.5000,-999.000000,-999.000000,0,45000.0,-999.000000,-999.0000,0.000000,61.140719,0.000000,0.0,-999.0000,0.250000,90.0,-999.0000,1.0000,0.0000,-999,-999.000000,0.700000,0.000000,1.0,0.0000,0.0000,-9.990000e+02,0.000000,31,0.285714,1.0000,100.0000,3,1100000.0,9.978571e+08,0.0540,0.434382
11,1368031794049114114,train,0,0.0000,1.0000,2.445918e+07,0.000000,1.5000,0.3333,3.4774,0.0000,6.084384e+07,-999.0,-999.0000,0.235294,1.6611,0.5000,2,-999.000000,0.294118,63.0,5,0.000000e+00,-999,1.0000,0.380952,2.227592e+15,129.0,10.5000,0.0000,87,0.0965,0.0,1,-999.0000,10.5000,34.0,0.789474,1.0000,1.000000e+06,76000000.0,0.0,1044444.5,35.6154,0.0000,0.000000,0.523810,1.0,511.260826,1000000.0,...,27,8.000000,0.952381,-9.990000e+02,21.0,105340.5,1.0000,-999,1.0000,-999.0,79.0000,1.1938,0.000000,18.0,0.259868,0.5000,-999.000000,0.000000,7,30000.0,1.000000,-999.0000,0.000000,43.861448,0.018692,0.0,-999.0000,1.000000,27.0,-999.0000,1.0000,0.2517,1,1.019973,0.826972,0.095238,-999.0,0.5048,0.0000,-9.990000e+02,0.144828,26,0.047619,0.0000,66.6667,6,2000000.0,3.060000e+08,-999.0000,0.276466
12,1417221356516511744,train,0,0.2726,0.0000,9.512296e+05,0.000000,0.9444,0.2069,5.6127,15.0000,4.225974e+06,1.0,-999.0000,0.000000,0.1176,0.9444,2,1.200000,0.000000,1.0,4,6.761569e+05,1,0.6897,0.400000,2.846585e+15,6.0,1.6667,0.0000,29,0.0649,0.0,0,-999.0000,1.6000,65.0,0.538462,0.0000,3.471429e+06,2777000.0,3.0,356982.5,15.6429,1.3453,0.000000,0.187500,1.0,148.080094,45050000.0,...,100,1.900000,0.500000,0.000000e+00,5.0,312.5,0.9682,1,1.0838,-999.0,10929.4000,12.5714,0.000000,5.0,0.000000,0.9000,-999.000000,0.372678,6,30000.0,1.000000,1.2359,0.000000,51.967137,0.047619,0.0,0.0200,0.500000,101.0,5.6218,0.9947,-0.1999,1,0.998824,0.689189,0.125000,1.0,0.4163,0.4725,8.000000e+06,0.150000,30,0.187500,0.0000,10.0000,4,24300000.0,9.469231e+06,0.0736,0.377852
13,1298858573531099136,train,0,0.4545,1.0000,8.500000e+05,0.000000,1.3333,0.5714,5.0611,0.3333,4.138077e+06,-999.0,-999.0000,0.000000,0.6036,0.6667,2,1.333333,1.000000,-999.0,3,0.000000e+00,4,1.1429,0.666667,2.311653e+15,51.0,3.3333,0.0000,-999,0.0897,1.0,1,5.0613,3.3333,58.0,1.000000,2.0000,-9.990000e+02,700000.0,1.0,850000.0,28.7500,0.0000,0.000000,0.500000,-999.0,75.317107,800000.0,...,16,2.000000,0.333333,0.000000e+00,10.0,12800.0,1.0000,1,1.0000,-999.0,76.5000,3.7525,0.000000,13.0,0.020408,0.6667,-999.000000,0.471405,3,-999.0,1.000000,5.0493,0.000000,21.491083,0.000000,0.0,-999.0000,0.285714,16.0,5.0493,1.0000,1.2717,-999,1.000000,0.693878,0.166667,1.0,0.1800,0.0000,-9.990000e+02,0.133333,8,0.000000,3.0000,87.5000,21,-999.0,8.929671e+08,0.0703,0.343779
14,1352487779208704000,train,0,0.4219,0.0000,2.162000e+06,0.000000,1.3333,0.4342,6.1063,2.0000,8.679370e+05,-999.0,0.8754,0.000000,1.3701,1.1111,0,-999.000000,0.000000,-999.0,3,0.000000e+00,-999,0.9305,0.333333,2.236606e+15,51.0,1.0000,0.0000,-999,0.1128,3.0,2,4.0136,1.2500,60.0,1.000000,1.7500,-9.990000e+02,4985000.0,5.0,712500.0,7.0000,1.0362,0.000000,0.000000,-999.0,-999.000000,2700000.0,...,14,2.400000,1.000000,8.844735e+14,3.0,16200.0,1.0661,-999,1.0000,-999.0,93.0000,2.1885,0.000000,21.0,0.000000,1.1250,-999.000000,-999.000000,0,325000.0,-999.000000,1.6357,0.000000,114.333819,0.071429,0.0,9.2208,1.000000,52.0,6.1838,1.0000,0.0000,-999,-999.000000,0.785714,0.000000,1.0,0.4967,1.0149,2.100000e+06,0.000000,28,0.000000,1.5000,13.3333,0,-999.0,1.000000e+07,0.1052,0.366781
15,1426018629600296960,train,0,1.0000,1.0000,1.849025e+06,0.000000,0.7500,1.0000,5.8442,1.0000,1.801109e+06,1.0,-999.0000,0.000000,1.3975,0.7500,4,1.000000,0.000000,1.0,2,0.000000e+00,1,1.0000,0.666667,1.110130e+16,-999.0,1.3333,1.0000,97,0.0082,1.0,0,-999.0000,1.2000,11.0,0.500000,1.0000,-9.990000e+02,4400000.0,1.0,1200000.0,-999.0000,0.0000,0.000000,0.250000,1.0,67.111847,1100000.0,...,-999,1.500000,0.333333,0.000000e+00,4.0,-999.0,1.0000,1,1.0000,-999.0,23.5000,-999.0000,0.000000,-999.0,0.102564,0.6667,-999.000000,0.745356,6,109992.0,0.330688,6.3170,0.000000,27.369827,0.000000,0.0,-999.0000,0.617284,56.0,12.5005,1.0000,-999.0000,1,0.827735,0.794872,0.333333,1.0,0.1389,0.0000,-9.990000e+02,0.035714,26,0.166667,1.0000,-999.0000,9,-999.0,1.537500e+08,0.0082,0.240966
16,1312953433238188032,train,0,-999.0000,-999.0000,1.168376e+06,0.000000,0.0000,-999.0000,-999.0000,0.0000,1.131425e+06,-999.0,-999.0000,0.000000,-999.0000,0.0000,0,-999.000000,0.142857,-999.0,3,2.701149e+05,-999,-999.0000,0.647059,2.510460e+15,136.0,2.6667,-999.0000,55,0.0649,0.0,5,-999.0000,2.5000,84.0,0.857143,-999.0000,-9.990000e+02,228990.0,0.0,258550.0,22.2143,-999.0000,0.000000,0.352941,1.0,0.000000,-999.0,...,64,1.500000,0.473684,2.375716e+13,8.0,44402.0,-999.0000,-999,1.0210,-999.0,43975.6818,1.1294,0.000000,25.0,0.000000,0.0000,-999.000000,-999.000000,1,594100.0,-999.000000,-999.0000,0.000000,29.427612,0.000000,0.0,-999.0000,1.000000,90.0,-999.0000,1.0000,0.0853,-999,0.688506,0.597015,0.000000,5.0,0.3408,-999.0000,-9.990000e+02,0.056604,21,0.052632,-999.0000,26.9841,17,-999.0,2.820556e+08,0.0617,0.081585
17,1344837197652209664,train,1,0.6495,0.6000,2.436000e+06,0.000000,1.1429,0.6383,4.0102,2.7500,5.446530e+06,-999.0,3.8977,0.000000,1.5935,0.9286,2,1.000000,0.333333,-999.0,3,4.362121e+07,1,0.8298,0.636364,1.260603e+15,118.0,1.0000,0.6000,117,0.1072,3.0,0,4.0102,1.0000,126.0,0.833333,1.7500,-9.990000e+02,2316000.0,10.0,33333.0,26.3125,0.0000,0.000000,0.363636,1.0,84.500000,4900000.0,...,50,1.000000,0.454545,3.696510e+14,1.0,71820.5,1.0000,-999,1.6811,-999.0,349.6250,2.1098,0.000000,23.0,0.013699,0.9091,-999.000000,0.500000,2,250788.0,0.363636,1.7252,0.000000,84.534285,0.000000,0.0,-999.0000,0.448000,86.0,6.4603,1.0000,0.3458,-999,1.002013,0.876712,0.181818,1.0,0.2160,0.0000,-9.990000e+02,0.222222,25,0.000000,2.0000,100.0000,9,-999.0,2.681768e+08,0.1042,0.186059

In [74]:
#计算ks
print('训练集ks：',round(cal_ks(pred_train['predprob'].values,train_data['label'].values) * 100,2)) #cal_ks(预测概率值，真实标签类别值)
print('测试集ks：',round(cal_ks(pred_test['predprob'].values,test_data['label'].values) * 100,2))
print('验证集ks：',round(cal_ks(pred_valid['predprob'].values,pred_valid['label'].values) * 100,2))
#计算auc
print("    ")
print('训练集AUC:',round(roc_auc_score(y_train, pred_train[["predprob"]]),2))   #roc_auc_score(真实标签类别,预测概率值)
print('测试集AUC:',round(roc_auc_score(y_test, pred_test[["predprob"]]),2))
print('验证集AUC:',round(roc_auc_score(y_valid, pred_valid[["predprob"]]),2))

训练集ks： 27.35
测试集ks： 25.88
验证集ks： 26.57

训练集AUC: 0.69
测试集AUC: 0.68
验证集AUC: 0.67

## 统计psi

## 统计排序性

In [75]:
model.booster_.save_model('/home/zengjunyao/notebook/to_zjy_模型训练/model_train_result/score_af_wf_1027.txt')